souffle: souffle::Interpreter Class Reference
souffle::Interpreter Class Reference
Interpreter executing a RAM translation unit.
#include <Interpreter.h>
Public Member Functions
void executeMain ()
Execute main program.
void executeSubroutine (const RamStatement &stmt, const std::vector< RamDomain > &arguments, std::vector< RamDomain > &returnValues, std::vector< bool > &returnErrors)
Execute subroutine.
RamTranslationUnit & getTranslationUnit ()
Get translation unit.
Interpreter (RamTranslationUnit &tUnit)
virtual ~Interpreter ()
Protected Types
using relation_map = std::map< std::string, InterpreterRelation * >
relation environment type
Protected Member Functions
void createRelation (const RamRelation &id)
void dropRelation (const RamRelation &id)
Drop relation.
bool evalCond (const RamCondition &cond, const InterpreterContext &ctxt=InterpreterContext())
Evaluate conditions.
RamDomain evalExpr (const RamExpression &value, const InterpreterContext &ctxt=InterpreterContext())
Evaluate value.
void evalOp (const RamOperation &op, const InterpreterContext &args=InterpreterContext())
Evaluate operation.
void evalStmt (const RamStatement &stmt)
Evaluate statement.
int getCounter () const
Get counter.
size_t getIterationNumber () const
Get Iteration Number.
InterpreterRelation & getRelation (const std::string &name)
Get relation.
InterpreterRelation & getRelation (const RamRelation &id)
Get relation.
relation_map & getRelationMap () const
Get relation map.
SymbolTable & getSymbolTable ()
Get symbol table.
int incCounter ()
Increment counter.
void incIterationNumber ()
Increment iteration number.
void * loadDLL ()
Load dll.
void resetIterationNumber ()
Reset iteration number.
void swapRelation (const RamRelation &ramRel1, const RamRelation &ramRel2)
Swap relation.
Private Attributes
int counter
counter for $ operator
void * dll
Dynamic library for user-defined functors.
relation_map environment
relation environment
std::map< std::string, std::map< size_t, size_t > > frequencies
counters for atom profiling
friend InterpreterProgInterface
size_t iteration
iteration number (in a fix-point calculation)
std::map< std::string, std::atomic< size_t > > reads
counters for non-existence checks
RamTranslationUnit & translationUnit
RAM translation Unit.
Detailed Description
Interpreter executing a RAM translation unit.
Definition at line 51 of file Interpreter.h.
Member Typedef Documentation
using souffle::Interpreter::relation_map = std::map<std::string, InterpreterRelation*> protected
relation environment type
Definition at line 74 of file Interpreter.h.
Constructor & Destructor Documentation
souffle::Interpreter::Interpreter (RamTranslationUnit & tUnit) inline
Definition at line 53 of file Interpreter.h.
 : translationUnit(tUnit), counter(0), iteration(0), dll(nullptr) {}
virtual souffle::Interpreter::~Interpreter () inline virtual
Definition at line 54 of file Interpreter.h.
References environment.
{
         for (auto& x : environment) {
             delete x.second;
         }
     }
Member Function Documentation
void souffle::Interpreter::createRelation (const RamRelation & id) inline protected
Definition at line 118 of file Interpreter.h.
References environment, and souffle::EQREL.
Referenced by evalStmt().
{
         InterpreterRelation* res = nullptr;
         assert(environment.find(id.getName()) == environment.end());
         if (id.getRepresentation() == RelationRepresentation::EQREL) {
             res = new InterpreterEqRelation(id.getArity());
         } else {
             res = new InterpreterRelation(id.getArity());
         }
         environment[id.getName()] = res;
     }
void souffle::Interpreter::dropRelation (const RamRelation & id) inline protected
Drop relation.
Definition at line 148 of file Interpreter.h.
References environment, souffle::getName, and getRelation().
Referenced by evalStmt().
{
         InterpreterRelation& rel = getRelation(id);
         environment.erase(id.getName());
         delete &rel;
     }
bool souffle::Interpreter::evalCond (const RamCondition & cond, const InterpreterContext & ctxt = InterpreterContext()) protected
Evaluate conditions.
Evaluate RAM Condition.
Definition at line 288 of file Interpreter.cpp.
References arity, souffle::Global::config(), souffle::CONTAINS, souffle::EQ, evalExpr(), souffle::InterpreterRelation::exists(), souffle::GE, souffle::RamTranslationUnit::getAnalysis(), souffle::InterpreterRelation::getArity(), souffle::InterpreterRelation::getIndex(), souffle::RamExistenceCheckAnalysis::getKey(), souffle::RamProvenanceExistenceCheckAnalysis::getKey(), souffle::RamConjunction::getLHS(), souffle::RamConstraint::getLHS(), souffle::RamRelation::getName(), souffle::RamNegation::getOperand(), souffle::RamConstraint::getOperator(), getRelation(), souffle::RamAbstractExistenceCheck::getRelation(), souffle::RamEmptinessCheck::getRelation(), souffle::RamConjunction::getRHS(), souffle::RamConstraint::getRHS(), getSymbolTable(), getTranslationUnit(), souffle::RamAbstractExistenceCheck::getValues(), souffle::GT, high, i, souffle::RamRelation::isTemp(), souffle::RamExistenceCheckAnalysis::isTotal(), l, souffle::LE, lhs, low, souffle::LT, souffle::MATCH, MAX_RAM_DOMAIN, MIN_RAM_DOMAIN, souffle::NE, souffle::NOT_CONTAINS, souffle::NOT_MATCH, reads, souffle::SymbolTable::resolve(), and rhs.
Referenced by evalOp(), and evalStmt().
{
     class ConditionEvaluator : public RamVisitor<bool> {
         Interpreter& interpreter;
         const InterpreterContext& ctxt;
         RamExistenceCheckAnalysis* existCheckAnalysis;
         RamProvenanceExistenceCheckAnalysis* provExistCheckAnalysis;
     public:
         ConditionEvaluator(Interpreter& interp, const InterpreterContext& ctxt)
                 : interpreter(interp), ctxt(ctxt),
                   existCheckAnalysis(interp.getTranslationUnit().getAnalysis<RamExistenceCheckAnalysis>()),
                   provExistCheckAnalysis(
                           interp.getTranslationUnit().getAnalysis<RamProvenanceExistenceCheckAnalysis>()) {}
         // -- connectors operators --
         bool visitConjunction(const RamConjunction& conj) override {
             return visit(conj.getLHS()) && visit(conj.getRHS());
         }
         bool visitNegation(const RamNegation& neg) override {
             return !visit(neg.getOperand());
         }
         // -- relation operations --
         bool visitEmptinessCheck(const RamEmptinessCheck& emptiness) override {
             return interpreter.getRelation(emptiness.getRelation()).empty();
         }
         bool visitExistenceCheck(const RamExistenceCheck& exists) override {
             const InterpreterRelation& rel = interpreter.getRelation(exists.getRelation());
             // construct the pattern tuple
             auto arity = rel.getArity();
             auto values = exists.getValues();
             if (Global::config().has("profile") && !exists.getRelation().isTemp()) {
                 interpreter.reads[exists.getRelation().getName()]++;
             }
             // for total we use the exists test
             if (existCheckAnalysis->isTotal(&exists)) {
                 RamDomain tuple[arity];
                 for (size_t i = 0; i < arity; i++) {
                     tuple[i] = (values[i]) ? interpreter.evalExpr(*values[i], ctxt) : MIN_RAM_DOMAIN;
                 }
                 return rel.exists(tuple);
             }
             // for partial we search for lower and upper boundaries
             RamDomain low[arity];
             RamDomain high[arity];
             for (size_t i = 0; i < arity; i++) {
                 low[i] = (values[i]) ? interpreter.evalExpr(*values[i], ctxt) : MIN_RAM_DOMAIN;
                 high[i] = (values[i]) ? low[i] : MAX_RAM_DOMAIN;
             }
             // obtain index
             auto idx = rel.getIndex(existCheckAnalysis->getKey(&exists));
             auto range = idx->lowerUpperBound(low, high);
             return range.first != range.second;  // if there is something => done
         }
         bool visitProvenanceExistenceCheck(const RamProvenanceExistenceCheck& provExists) override {
             const InterpreterRelation& rel = interpreter.getRelation(provExists.getRelation());
             // construct the pattern tuple
             auto arity = rel.getArity();
             auto values = provExists.getValues();
             // for partial we search for lower and upper boundaries
             RamDomain low[arity];
             RamDomain high[arity];
             for (size_t i = 0; i < arity - 2; i++) {
                 low[i] = (values[i]) ? interpreter.evalExpr(*values[i], ctxt) : MIN_RAM_DOMAIN;
                 high[i] = (values[i]) ? low[i] : MAX_RAM_DOMAIN;
             }
             low[arity - 2] = MIN_RAM_DOMAIN;
             low[arity - 1] = MIN_RAM_DOMAIN;
             high[arity - 2] = MAX_RAM_DOMAIN;
             high[arity - 1] = MAX_RAM_DOMAIN;
             // obtain index
             auto idx = rel.getIndex(provExistCheckAnalysis->getKey(&provExists));
             auto range = idx->lowerUpperBound(low, high);
             return range.first != range.second;  // if there is something => done
         }
         // -- comparison operators --
         bool visitConstraint(const RamConstraint& relOp) override {
             RamDomain lhs = interpreter.evalExpr(*relOp.getLHS(), ctxt);
             RamDomain rhs = interpreter.evalExpr(*relOp.getRHS(), ctxt);
             switch (relOp.getOperator()) {
                 case BinaryConstraintOp::EQ:
                     return lhs == rhs;
                 case BinaryConstraintOp::NE:
                     return lhs != rhs;
                 case BinaryConstraintOp::LT:
                     return lhs < rhs;
                 case BinaryConstraintOp::LE:
                     return lhs <= rhs;
                 case BinaryConstraintOp::GT:
                     return lhs > rhs;
                 case BinaryConstraintOp::GE:
                     return lhs >= rhs;
                 case BinaryConstraintOp::MATCH: {
                     RamDomain l = interpreter.evalExpr(*relOp.getLHS(), ctxt);
                     RamDomain r = interpreter.evalExpr(*relOp.getRHS(), ctxt);
                     const std::string& pattern = interpreter.getSymbolTable().resolve(l);
                     const std::string& text = interpreter.getSymbolTable().resolve(r);
                     bool result = false;
                     try {
                         result = std::regex_match(text, std::regex(pattern));
                     } catch (...) {
                         std::cerr << "warning: wrong pattern provided for match(\"" << pattern << "\",\""
                                   << text << "\").\n";
                     }
                     return result;
                 }
                 case BinaryConstraintOp::NOT_MATCH: {
                     RamDomain l = interpreter.evalExpr(*relOp.getLHS(), ctxt);
                     RamDomain r = interpreter.evalExpr(*relOp.getRHS(), ctxt);
                     const std::string& pattern = interpreter.getSymbolTable().resolve(l);
                     const std::string& text = interpreter.getSymbolTable().resolve(r);
                     bool result = false;
                     try {
                         result = !std::regex_match(text, std::regex(pattern));
                     } catch (...) {
                         std::cerr << "warning: wrong pattern provided for !match(\"" << pattern << "\",\""
                                   << text << "\").\n";
                     }
                     return result;
                 }
                 case BinaryConstraintOp::CONTAINS: {
                     RamDomain l = interpreter.evalExpr(*relOp.getLHS(), ctxt);
                     RamDomain r = interpreter.evalExpr(*relOp.getRHS(), ctxt);
                     const std::string& pattern = interpreter.getSymbolTable().resolve(l);
                     const std::string& text = interpreter.getSymbolTable().resolve(r);
                     return text.find(pattern) != std::string::npos;
                 }
                 case BinaryConstraintOp::NOT_CONTAINS: {
                     RamDomain l = interpreter.evalExpr(*relOp.getLHS(), ctxt);
                     RamDomain r = interpreter.evalExpr(*relOp.getRHS(), ctxt);
                     const std::string& pattern = interpreter.getSymbolTable().resolve(l);
                     const std::string& text = interpreter.getSymbolTable().resolve(r);
                     return text.find(pattern) == std::string::npos;
                 }
                 default:
                     assert(false && "unsupported operator");
                     return false;
             }
         }
         bool visitNode(const RamNode& node) override {
             std::cerr << "Unsupported node type: " << typeid(node).name() << "\n";
             assert(false && "Unsupported Node Type!");
             return false;
         }
     };
     // run evaluator
     return ConditionEvaluator(*this, ctxt)(cond);
 }
RamDomain souffle::Interpreter::evalExpr (const RamExpression & value, const InterpreterContext & ctxt = InterpreterContext()) protected
Evaluate value.
Evaluate RAM Expression.
Unary Functor Operators
Binary Functor Operators
Ternary Functor Operators
Undefined
Definition at line 62 of file Interpreter.cpp.
References souffle::ADD, arity, souffle::BAND, souffle::BNOT, souffle::BOR, souffle::BXOR, souffle::CAT, souffle::DIV, souffle::EXP, souffle::RamUserDefinedOperator::getArgCount(), souffle::InterpreterContext::getArgument(), souffle::RamUserDefinedOperator::getArgument(), souffle::RamArgument::getArgument(), souffle::RamIntrinsicOperator::getArguments(), souffle::RamPackRecord::getArguments(), souffle::RamNumber::getConstant(), souffle::RamElementAccess::getElement(), souffle::RamElementAccess::getIdentifier(), souffle::RamUserDefinedOperator::getName(), souffle::RamIntrinsicOperator::getOperator(), getSymbolTable(), souffle::RamUserDefinedOperator::getType(), i, incCounter(), souffle::LAND, souffle::LNOT, loadDLL(), souffle::SymbolTable::lookup(), souffle::LOR, souffle::MAX, souffle::MIN, souffle::MOD, souffle::MUL, souffle::NEG, souffle::ORD, souffle::pack(), souffle::SymbolTable::resolve(), SOUFFLE_DLL, souffle::profile::ss, stord, str, souffle::STRLEN, souffle::SUB, souffle::SUBSTR, souffle::TONUMBER, and souffle::TOSTRING.
Referenced by evalCond(), evalOp(), and evalStmt().
{
     class ExpressionEvaluator : public RamVisitor<RamDomain> {
         Interpreter& interpreter;
         const InterpreterContext& ctxt;
     public:
         ExpressionEvaluator(Interpreter& interp, const InterpreterContext& ctxt)
                 : interpreter(interp), ctxt(ctxt) {}
         RamDomain visitNumber(const RamNumber& num) override {
             return num.getConstant();
         }
         RamDomain visitElementAccess(const RamElementAccess& access) override {
             return ctxt[access.getIdentifier()][access.getElement()];
         }
         RamDomain visitAutoIncrement(const RamAutoIncrement&) override {
             return interpreter.incCounter();
         }
         // intrinsic functors
         RamDomain visitIntrinsicOperator(const RamIntrinsicOperator& op) override {
             const auto& args = op.getArguments();
             switch (op.getOperator()) {
                 /** Unary Functor Operators */
                 case FunctorOp::ORD:
                     return visit(args[0]);
                 case FunctorOp::STRLEN:
                     return interpreter.getSymbolTable().resolve(visit(args[0])).size();
                 case FunctorOp::NEG:
                     return -visit(args[0]);
                 case FunctorOp::BNOT:
                     return ~visit(args[0]);
                 case FunctorOp::LNOT:
                     return !visit(args[0]);
                 case FunctorOp::TONUMBER: {
                     RamDomain result = 0;
                     try {
                         result = stord(interpreter.getSymbolTable().resolve(visit(args[0])));
                     } catch (...) {
                         std::cerr << "error: wrong string provided by to_number(\"";
                         std::cerr << interpreter.getSymbolTable().resolve(visit(args[0]));
                         std::cerr << "\") functor.\n";
                         raise(SIGFPE);
                     }
                     return result;
                 }
                 case FunctorOp::TOSTRING:
                     return interpreter.getSymbolTable().lookup(std::to_string(visit(args[0])));
                 /** Binary Functor Operators */
                 case FunctorOp::ADD: {
                     return visit(args[0]) + visit(args[1]);
                 }
                 case FunctorOp::SUB: {
                     return visit(args[0]) - visit(args[1]);
                 }
                 case FunctorOp::MUL: {
                     return visit(args[0]) * visit(args[1]);
                 }
                 case FunctorOp::DIV: {
                     return visit(args[0]) / visit(args[1]);
                 }
                 case FunctorOp::EXP: {
                     return std::pow(visit(args[0]), visit(args[1]));
                 }
                 case FunctorOp::MOD: {
                     return visit(args[0]) % visit(args[1]);
                 }
                 case FunctorOp::BAND: {
                     return visit(args[0]) & visit(args[1]);
                 }
                 case FunctorOp::BOR: {
                     return visit(args[0]) | visit(args[1]);
                 }
                 case FunctorOp::BXOR: {
                     return visit(args[0]) ^ visit(args[1]);
                 }
                 case FunctorOp::LAND: {
                     return visit(args[0]) && visit(args[1]);
                 }
                 case FunctorOp::LOR: {
                     return visit(args[0]) || visit(args[1]);
                 }
                 case FunctorOp::MAX: {
                     auto result = visit(args[0]);
                     for (size_t i = 1; i < args.size(); i++) {
                         result = std::max(result, visit(args[i]));
                     }
                     return result;
                 }
                 case FunctorOp::MIN: {
                     auto result = visit(args[0]);
                     for (size_t i = 1; i < args.size(); i++) {
                         result = std::min(result, visit(args[i]));
                     }
                     return result;
                 }
                 case FunctorOp::CAT: {
                     std::stringstream ss;
                     for (auto& arg : args) {
                         ss << interpreter.getSymbolTable().resolve(visit(arg));
                     }
                     return interpreter.getSymbolTable().lookup(ss.str());
                 }
                 /** Ternary Functor Operators */
                 case FunctorOp::SUBSTR: {
                     auto symbol = visit(args[0]);
                     const std::string& str = interpreter.getSymbolTable().resolve(symbol);
                     auto idx = visit(args[1]);
                     auto len = visit(args[2]);
                     std::string sub_str;
                     try {
                         sub_str = str.substr(idx, len);
                     } catch (...) {
                         std::cerr << "warning: wrong index position provided by substr(\"";
                         std::cerr << str << "\"," << (int32_t)idx << "," << (int32_t)len << ") functor.\n";
                     }
                     return interpreter.getSymbolTable().lookup(sub_str);
                 }
                 /** Undefined */
                 default: {
                     assert(false && "unsupported operator");
                     return 0;
                 }
             }
         }
         RamDomain visitUserDefinedOperator(const RamUserDefinedOperator& op) override {
             // get name and type
             const std::string& name = op.getName();
             const std::string& type = op.getType();
             // load DLL (if not done yet)
             void* handle = interpreter.loadDLL();
             void (*fn)() = (void (*)())dlsym(handle, name.c_str());
             if (fn == nullptr) {
                 std::cerr << "Cannot find user-defined operator " << name << " in " << SOUFFLE_DLL
                           << std::endl;
                 exit(1);
             }
             // prepare dynamic call environment
             size_t arity = op.getArgCount();
             ffi_cif cif;
             ffi_type* args[arity];
             void* values[arity];
             RamDomain intVal[arity];
             const char* strVal[arity];
             ffi_arg rc;
             /* Initialize arguments for ffi-call */
             for (size_t i = 0; i < arity; i++) {
                 RamDomain arg = visit(op.getArgument(i));
                 if (type[i] == 'S') {
                     args[i] = &ffi_type_pointer;
                     strVal[i] = interpreter.getSymbolTable().resolve(arg).c_str();
                     values[i] = &strVal[i];
                 } else {
                     args[i] = &ffi_type_uint32;
                     intVal[i] = arg;
                     values[i] = &intVal[i];
                 }
             }
             // call external function
             if (type[arity] == 'N') {
                 // Initialize for numerical return value
                 if (ffi_prep_cif(&cif, FFI_DEFAULT_ABI, arity, &ffi_type_uint32, args) != FFI_OK) {
                     std::cerr << "Failed to prepare CIF for user-defined operator ";
                     std::cerr << name << std::endl;
                     exit(1);
                 }
             } else {
                 // Initialize for string return value
                 if (ffi_prep_cif(&cif, FFI_DEFAULT_ABI, arity, &ffi_type_pointer, args) != FFI_OK) {
                     std::cerr << "Failed to prepare CIF for user-defined operator ";
                     std::cerr << name << std::endl;
                     exit(1);
                 }
             }
             ffi_call(&cif, fn, &rc, values);
             RamDomain result;
             if (type[arity] == 'N') {
                 result = ((RamDomain)rc);
             } else {
                 result = interpreter.getSymbolTable().lookup(((const char*)rc));
             }
             return result;
         }
         // -- records --
         RamDomain visitPackRecord(const RamPackRecord& pr) override {
             auto values = pr.getArguments();
             auto arity = values.size();
             RamDomain data[arity];
             for (size_t i = 0; i < arity; ++i) {
                 data[i] = visit(values[i]);
             }
             return pack(data, arity);
         }
         // -- subroutine argument
         RamDomain visitArgument(const RamArgument& arg) override {
             return ctxt.getArgument(arg.getArgument());
         }
         // -- safety net --
         RamDomain visitNode(const RamNode& node) override {
             std::cerr << "Unsupported node type: " << typeid(node).name() << "\n";
             assert(false && "Unsupported Node Type!");
             return 0;
         }
     };
     // create and run evaluator
     return ExpressionEvaluator(*this, ctxt)(expr);
 }
void souffle::Interpreter::evalOp (const RamOperation & op, const InterpreterContext & args = InterpreterContext()) protected
Evaluate operation.
Evaluate RAM operation.
Definition at line 455 of file Interpreter.cpp.
References souffle::InterpreterContext::addReturnValue(), arity, souffle::Global::config(), souffle::RamAggregate::COUNT, evalCond(), evalExpr(), frequencies, souffle::RamTranslationUnit::getAnalysis(), souffle::InterpreterContext::getArguments(), souffle::InterpreterRelation::getArity(), souffle::RamRelation::getArity(), souffle::RamUnpackRecord::getArity(), souffle::RamFilter::getCondition(), souffle::RamOperationDepthAnalysis::getDepth(), souffle::RamAggregate::getExpression(), souffle::RamAggregate::getFunction(), souffle::RamSearch::getIdentifier(), souffle::InterpreterRelation::getIndex(), getIterationNumber(), souffle::RamNestedOperation::getOperation(), souffle::RamAggregate::getPattern(), souffle::RamNestedOperation::getProfileText(), souffle::RamIndexScan::getRangePattern(), souffle::RamIndexScanKeysAnalysis::getRangeQueryColumns(), souffle::RamAggregate::getRangeQueryColumns(), souffle::RamUnpackRecord::getReferenceLevel(), souffle::RamUnpackRecord::getReferencePosition(), getRelation(), souffle::RamRelationSearch::getRelation(), souffle::RamAggregate::getRelation(), souffle::RamProject::getRelation(), souffle::InterpreterContext::getReturnErrors(), souffle::InterpreterContext::getReturnValues(), getTranslationUnit(), souffle::RamProject::getValues(), souffle::RamReturn::getValues(), i, souffle::InterpreterRelation::insert(), souffle::isNull(), low, souffle::RamAggregate::MAX, MAX_RAM_DOMAIN, souffle::RamAggregate::MIN, MIN_RAM_DOMAIN, souffle::InterpreterContext::setReturnValues(), souffle::RamAggregate::SUM, translationUnit, and souffle::unpack().
Referenced by evalStmt(), and executeSubroutine().
{
     class OperationEvaluator : public RamVisitor<void> {
         Interpreter& interpreter;
         InterpreterContext& ctxt;
         RamIndexScanKeysAnalysis* keysAnalysis;
     public:
         OperationEvaluator(Interpreter& interp, InterpreterContext& ctxt)
                 : interpreter(interp), ctxt(ctxt),
                   keysAnalysis(interp.getTranslationUnit().getAnalysis<RamIndexScanKeysAnalysis>()) {}
         // -- Operations -----------------------------
         void visitNestedOperation(const RamNestedOperation& nested) override {
             visit(nested.getOperation());
         }
         void visitSearch(const RamSearch& search) override {
             visitNestedOperation(search);
             if (Global::config().has("profile") && !search.getProfileText().empty()) {
                 interpreter.frequencies[search.getProfileText()][interpreter.getIterationNumber()]++;
             }
         }
         void visitScan(const RamScan& scan) override {
             // get the targeted relation
             const InterpreterRelation& rel = interpreter.getRelation(scan.getRelation());
             // use simple iterator
             for (const RamDomain* cur : rel) {
                 ctxt[scan.getIdentifier()] = cur;
                 visitSearch(scan);
             }
         }
         void visitIndexScan(const RamIndexScan& scan) override {
             // get the targeted relation
             const InterpreterRelation& rel = interpreter.getRelation(scan.getRelation());
             // create pattern tuple for range query
             auto arity = rel.getArity();
             RamDomain low[arity];
             RamDomain hig[arity];
             auto pattern = scan.getRangePattern();
             for (size_t i = 0; i < arity; i++) {
                 if (pattern[i] != nullptr) {
                     low[i] = interpreter.evalExpr(*pattern[i], ctxt);
                     hig[i] = low[i];
                 } else {
                     low[i] = MIN_RAM_DOMAIN;
                     hig[i] = MAX_RAM_DOMAIN;
                 }
             }
             // obtain index
             auto idx = rel.getIndex(keysAnalysis->getRangeQueryColumns(&scan), nullptr);
             // get iterator range
             auto range = idx->lowerUpperBound(low, hig);
             // conduct range query
             for (auto ip = range.first; ip != range.second; ++ip) {
                 const RamDomain* data = *(ip);
                 ctxt[scan.getIdentifier()] = data;
                 visitSearch(scan);
             }
         }
         void visitUnpackRecord(const RamUnpackRecord& lookup) override {
             // get reference
             RamDomain ref = ctxt[lookup.getReferenceLevel()][lookup.getReferencePosition()];
             // check for null
             if (isNull(ref)) {
                 return;
             }
             // update environment variable
             auto arity = lookup.getArity();
             const RamDomain* tuple = unpack(ref, arity);
             // save reference to temporary value
             ctxt[lookup.getIdentifier()] = tuple;
             // run nested part - using base class visitor
             visitSearch(lookup);
         }
         void visitAggregate(const RamAggregate& aggregate) override {
             // get the targeted relation
             const InterpreterRelation& rel = interpreter.getRelation(aggregate.getRelation());
             // initialize result
             RamDomain res = 0;
             switch (aggregate.getFunction()) {
                 case RamAggregate::MIN:
                     res = MAX_RAM_DOMAIN;
                     break;
                 case RamAggregate::MAX:
                     res = MIN_RAM_DOMAIN;
                     break;
                 case RamAggregate::COUNT:
                     res = 0;
                     break;
                 case RamAggregate::SUM:
                     res = 0;
                     break;
             }
             // init temporary tuple for this level
             auto arity = rel.getArity();
             // get lower and upper boundaries for iteration
             const auto& pattern = aggregate.getPattern();
             RamDomain low[arity];
             RamDomain hig[arity];
             for (size_t i = 0; i < arity; i++) {
                 if (pattern[i] != nullptr) {
                     low[i] = interpreter.evalExpr(*pattern[i], ctxt);
                     hig[i] = low[i];
                 } else {
                     low[i] = MIN_RAM_DOMAIN;
                     hig[i] = MAX_RAM_DOMAIN;
                 }
             }
             // obtain index
             auto idx = rel.getIndex(aggregate.getRangeQueryColumns());
             // get iterator range
             auto range = idx->lowerUpperBound(low, hig);
             // check for emptiness
             if (aggregate.getFunction() != RamAggregate::COUNT) {
                 if (range.first == range.second) {
                     return;  // no elements => no min/max
                 }
             }
             // iterate through values
             for (auto ip = range.first; ip != range.second; ++ip) {
                 // link tuple
                 const RamDomain* data = *(ip);
                 ctxt[aggregate.getIdentifier()] = data;
                 // count is easy
                 if (aggregate.getFunction() == RamAggregate::COUNT) {
                     ++res;
                     continue;
                 }
                 // aggregation is a bit more difficult
                 // eval target expression
                 RamDomain cur = interpreter.evalExpr(*aggregate.getExpression(), ctxt);
                 switch (aggregate.getFunction()) {
                     case RamAggregate::MIN:
                         res = std::min(res, cur);
                         break;
                     case RamAggregate::MAX:
                         res = std::max(res, cur);
                         break;
                     case RamAggregate::COUNT:
                         res = 0;
                         break;
                     case RamAggregate::SUM:
                         res += cur;
                         break;
                 }
             }
             // write result to environment
             RamDomain tuple[1];
             tuple[0] = res;
             ctxt[aggregate.getIdentifier()] = tuple;
             // run nested part - using base class visitor
             visitSearch(aggregate);
         }
         void visitFilter(const RamFilter& filter) override {
             // check condition
             if (interpreter.evalCond(filter.getCondition(), ctxt)) {
                 // process nested
                 visitNestedOperation(filter);
             }
             if (Global::config().has("profile") && !filter.getProfileText().empty()) {
                 interpreter.frequencies[filter.getProfileText()][interpreter.getIterationNumber()]++;
             }
         }
         void visitProject(const RamProject& project) override {
             // create a tuple of the proper arity (also supports arity 0)
             auto arity = project.getRelation().getArity();
             const auto& values = project.getValues();
             RamDomain tuple[arity];
             for (size_t i = 0; i < arity; i++) {
                 assert(values[i]);
                 tuple[i] = interpreter.evalExpr(*values[i], ctxt);
             }
             // insert in target relation
             InterpreterRelation& rel = interpreter.getRelation(project.getRelation());
             rel.insert(tuple);
         }
         // -- return from subroutine --
         void visitReturn(const RamReturn& ret) override {
             for (auto val : ret.getValues()) {
                 if (val == nullptr) {
                     ctxt.addReturnValue(0, true);
                 } else {
                     ctxt.addReturnValue(interpreter.evalExpr(*val, ctxt));
                 }
             }
         }
         // -- safety net --
         void visitNode(const RamNode& node) override {
             std::cerr << "Unsupported node type: " << typeid(node).name() << "\n";
             assert(false && "Unsupported Node Type!");
         }
     };
     // create and run interpreter for operations
     InterpreterContext ctxt(translationUnit.getAnalysis<RamOperationDepthAnalysis>()->getDepth(&op));
     ctxt.setReturnValues(args.getReturnValues());
     ctxt.setReturnErrors(args.getReturnErrors());
     ctxt.setArguments(args.getArguments());
     OperationEvaluator(*this, ctxt).visit(op);
 }
void souffle::Interpreter::evalStmt (const RamStatement & stmt) protected
Evaluate statement.
Evaluate RAM statement.
Definition at line 692 of file Interpreter.cpp.
References souffle::Lock::acquire(), arity, souffle::Global::config(), createRelation(), dropRelation(), e, evalCond(), evalExpr(), evalOp(), souffle::InterpreterRelation::extend(), souffle::RamRelation::getArity(), souffle::RamRelation::getAttributeTypeQualifiers(), souffle::RamLoop::getBody(), souffle::RamStratum::getBody(), souffle::RamExit::getCondition(), souffle::RamSwap::getFirstRelation(), souffle::RamStratum::getIndex(), souffle::IOSystem::getInstance(), souffle::RamLoad::getIODirectives(), souffle::RamStore::getIODirectives(), getIterationNumber(), souffle::RamLogTimer::getMessage(), souffle::RamDebugInfo::getMessage(), souffle::RamLogSize::getMessage(), souffle::RamRelation::getName(), souffle::RamQuery::getOperation(), souffle::getOutputLock(), souffle::IOSystem::getReader(), souffle::RamRelationStatement::getRelation(), getRelation(), souffle::RamLogTimer::getRelation(), souffle::RamSwap::getSecondRelation(), souffle::RamMerge::getSourceRelation(), souffle::RamLogTimer::getStatement(), souffle::RamDebugInfo::getStatement(), souffle::RamSequence::getStatements(), souffle::RamParallel::getStatements(), getSymbolTable(), souffle::RamMerge::getTargetRelation(), souffle::RamFact::getValues(), souffle::IOSystem::getWriter(), i, incIterationNumber(), souffle::InterpreterRelation::insert(), souffle::SignalHandler::instance(), souffle::ProfileEventSingleton::instance(), souffle::ProfileEventSingleton::makeQuantityEvent(), souffle::ProfileEventSingleton::makeStratumRecord(), souffle::InterpreterRelation::purge(), relation, resetIterationNumber(), souffle::SignalHandler::setMsg(), souffle::InterpreterRelation::size(), swapRelation(), and souffle::visitDepthFirst().
Referenced by executeMain().
{
     class StatementEvaluator : public RamVisitor<bool> {
         Interpreter& interpreter;
     public:
         StatementEvaluator(Interpreter& interp) : interpreter(interp) {}
         // -- Statements -----------------------------
         bool visitSequence(const RamSequence& seq) override {
             // process all statements in sequence
             for (const auto& cur : seq.getStatements()) {
                 if (!visit(cur)) {
                     return false;
                 }
             }
             // all processed successfully
             return true;
         }
         bool visitParallel(const RamParallel& parallel) override {
             // get statements to be processed in parallel
             const auto& stmts = parallel.getStatements();
             // special case: empty
             if (stmts.empty()) {
                 return true;
             }
             // special handling for a single child
             if (stmts.size() == 1) {
                 return visit(stmts[0]);
             }
             // parallel execution
             bool cond = true;
 #pragma omp parallel for reduction(&& : cond)
             for (size_t i = 0; i < stmts.size(); i++) {
                 cond = cond && visit(stmts[i]);
             }
             return cond;
         }
         bool visitLoop(const RamLoop& loop) override {
             interpreter.resetIterationNumber();
             while (visit(loop.getBody())) {
                 interpreter.incIterationNumber();
             }
             interpreter.resetIterationNumber();
             return true;
         }
         bool visitExit(const RamExit& exit) override {
             return !interpreter.evalCond(exit.getCondition());
         }
         bool visitLogTimer(const RamLogTimer& timer) override {
             if (timer.getRelation() == nullptr) {
                 Logger logger(timer.getMessage().c_str(), interpreter.getIterationNumber());
                 return visit(timer.getStatement());
             } else {
                 const InterpreterRelation& rel = interpreter.getRelation(*timer.getRelation());
                 Logger logger(timer.getMessage().c_str(), interpreter.getIterationNumber(),
                         std::bind(&InterpreterRelation::size, &rel));
                 return visit(timer.getStatement());
             }
         }
         bool visitDebugInfo(const RamDebugInfo& dbg) override {
             SignalHandler::instance()->setMsg(dbg.getMessage().c_str());
             return visit(dbg.getStatement());
         }
         bool visitStratum(const RamStratum& stratum) override {
             // TODO (lyndonhenry): should enable strata as subprograms for interpreter here
             // Record relations created in each stratum
             if (Global::config().has("profile")) {
                 std::map<std::string, size_t> relNames;
                 visitDepthFirst(stratum, [&](const RamCreate& create) {
                     relNames[create.getRelation().getName()] = create.getRelation().getArity();
                 });
                 for (const auto& cur : relNames) {
                     // Skip temporary relations, marked with '@'
                     if (cur.first[0] == '@') {
                         continue;
                     }
                     ProfileEventSingleton::instance().makeStratumRecord(
                             stratum.getIndex(), "relation", cur.first, "arity", std::to_string(cur.second));
                 }
             }
             return visit(stratum.getBody());
         }
         bool visitCreate(const RamCreate& create) override {
             interpreter.createRelation(create.getRelation());
             return true;
         }
         bool visitClear(const RamClear& clear) override {
             InterpreterRelation& rel = interpreter.getRelation(clear.getRelation());
             rel.purge();
             return true;
         }
         bool visitDrop(const RamDrop& drop) override {
             interpreter.dropRelation(drop.getRelation());
             return true;
         }
         bool visitLogSize(const RamLogSize& size) override {
             const InterpreterRelation& rel = interpreter.getRelation(size.getRelation());
             ProfileEventSingleton::instance().makeQuantityEvent(
                     size.getMessage(), rel.size(), interpreter.getIterationNumber());
             return true;
         }
         bool visitLoad(const RamLoad& load) override {
             for (IODirectives ioDirectives : load.getIODirectives()) {
                 try {
                     InterpreterRelation& relation = interpreter.getRelation(load.getRelation());
                     std::vector<bool> symbolMask;
                     for (auto& cur : load.getRelation().getAttributeTypeQualifiers()) {
                         symbolMask.push_back(cur[0] == 's');
                     }
                     IOSystem::getInstance()
                             .getReader(symbolMask, interpreter.getSymbolTable(), ioDirectives,
                                     Global::config().has("provenance"))
                             ->readAll(relation);
                 } catch (std::exception& e) {
                     std::cerr << "Error loading data: " << e.what() << "\n";
                 }
             }
             return true;
         }
         bool visitStore(const RamStore& store) override {
             for (IODirectives ioDirectives : store.getIODirectives()) {
                 try {
                     std::vector<bool> symbolMask;
                     for (auto& cur : store.getRelation().getAttributeTypeQualifiers()) {
                         symbolMask.push_back(cur[0] == 's');
                     }
                     IOSystem::getInstance()
                             .getWriter(symbolMask, interpreter.getSymbolTable(), ioDirectives,
                                     Global::config().has("provenance"))
                             ->writeAll(interpreter.getRelation(store.getRelation()));
                 } catch (std::exception& e) {
                     std::cerr << e.what();
                     exit(1);
                 }
             }
             return true;
         }
         bool visitFact(const RamFact& fact) override {
             auto arity = fact.getRelation().getArity();
             RamDomain tuple[arity];
             auto values = fact.getValues();
             for (size_t i = 0; i < arity; ++i) {
                 tuple[i] = interpreter.evalExpr(*values[i]);
             }
             interpreter.getRelation(fact.getRelation()).insert(tuple);
             return true;
         }
         bool visitQuery(const RamQuery& query) override {
             interpreter.evalOp(query.getOperation());
             return true;
         }
         bool visitMerge(const RamMerge& merge) override {
             // get involved relation
             InterpreterRelation& src = interpreter.getRelation(merge.getSourceRelation());
             InterpreterRelation& trg = interpreter.getRelation(merge.getTargetRelation());
             if (dynamic_cast<InterpreterEqRelation*>(&trg)) {
                 // expand src with the new knowledge generated by insertion.
                 src.extend(trg);
             }
             // merge in all elements
             trg.insert(src);
             // done
             return true;
         }
         bool visitSwap(const RamSwap& swap) override {
             interpreter.swapRelation(swap.getFirstRelation(), swap.getSecondRelation());
             return true;
         }
         // -- safety net --
         bool visitNode(const RamNode& node) override {
             auto lease = getOutputLock().acquire();
             (void)lease;
             std::cerr << "Unsupported node type: " << typeid(node).name() << "\n";
             assert(false && "Unsupported Node Type!");
             return false;
         }
     };
     // create and run interpreter for statements
     StatementEvaluator(*this).visit(stmt);
 }
void souffle::Interpreter::executeMain ()
Execute main program.
Execute main program of a translation unit.
Definition at line 902 of file Interpreter.cpp.
References souffle::Global::config(), souffle::SignalHandler::enableLogging(), evalStmt(), frequencies, souffle::RamProgram::getMain(), souffle::RamRelation::getName(), souffle::RamNestedOperation::getProfileText(), souffle::RamTranslationUnit::getProgram(), souffle::RamRelationStatement::getRelation(), souffle::SignalHandler::instance(), souffle::ProfileEventSingleton::instance(), souffle::main(), souffle::ProfileEventSingleton::makeConfigRecord(), souffle::ProfileEventSingleton::makeQuantityEvent(), souffle::ProfileEventSingleton::makeTimeEvent(), reads, souffle::SignalHandler::reset(), rule, souffle::SignalHandler::set(), souffle::ProfileEventSingleton::setOutputFile(), souffle::ProfileEventSingleton::startTimer(), souffle::ProfileEventSingleton::stopTimer(), translationUnit, and souffle::visitDepthFirst().
Referenced by getTranslationUnit().
{
     SignalHandler::instance()->set();
     if (Global::config().has("verbose")) {
         SignalHandler::instance()->enableLogging();
     }
     const RamStatement& main = *translationUnit.getProgram()->getMain();
     if (!Global::config().has("profile")) {
         evalStmt(main);
     } else {
         ProfileEventSingleton::instance().setOutputFile(Global::config().get("profile"));
         // Prepare the frequency table for threaded use
         visitDepthFirst(main, [&](const RamSearch& node) {
             if (!node.getProfileText().empty()) {
                 frequencies.emplace(node.getProfileText(), std::map<size_t, size_t>());
             }
         });
         // Enable profiling for execution of main
         ProfileEventSingleton::instance().startTimer();
         ProfileEventSingleton::instance().makeTimeEvent("@time;starttime");
         // Store configuration
         for (const auto& cur : Global::config().data()) {
             ProfileEventSingleton::instance().makeConfigRecord(cur.first, cur.second);
         }
         // Store count of relations
         size_t relationCount = 0;
         visitDepthFirst(main, [&](const RamCreate& create) {
             if (create.getRelation().getName()[0] != '@') {
                 ++relationCount;
                 reads[create.getRelation().getName()] = 0;
             }
         });
         ProfileEventSingleton::instance().makeConfigRecord("relationCount", std::to_string(relationCount));
         // Store count of rules
         size_t ruleCount = 0;
         visitDepthFirst(main, [&](const RamQuery& rule) { ++ruleCount; });
         ProfileEventSingleton::instance().makeConfigRecord("ruleCount", std::to_string(ruleCount));
         evalStmt(main);
         ProfileEventSingleton::instance().stopTimer();
         for (auto const& cur : frequencies) {
             for (auto const& iter : cur.second) {
                 ProfileEventSingleton::instance().makeQuantityEvent(cur.first, iter.second, iter.first);
             }
         }
         for (auto const& cur : reads) {
             ProfileEventSingleton::instance().makeQuantityEvent(
                     "@relation-reads;" + cur.first, cur.second, 0);
         }
     }
     SignalHandler::instance()->reset();
 }
void souffle::Interpreter::executeSubroutine (const RamStatement & stmt, const std::vector< RamDomain > & arguments, std::vector< RamDomain > & returnValues, std::vector< bool > & returnErrors)
Execute subroutine.
Definition at line 957 of file Interpreter.cpp.
References evalOp(), souffle::InterpreterContext::setArguments(), souffle::InterpreterContext::setReturnErrors(), and souffle::InterpreterContext::setReturnValues().
Referenced by getTranslationUnit().
{
     InterpreterContext ctxt;
     ctxt.setReturnValues(returnValues);
     ctxt.setReturnErrors(returnErrors);
     ctxt.setArguments(arguments);
     // run subroutine
     const RamOperation& op = static_cast<const RamQuery&>(stmt).getOperation();
     evalOp(op, ctxt);
 }
int souffle::Interpreter::getCounter () const inline protected
Get counter.
Definition at line 94 of file Interpreter.h.
References counter.
{
         return counter;
     }
size_t souffle::Interpreter::getIterationNumber () const inline protected
Get Iteration Number.
Definition at line 99 of file Interpreter.h.
References iteration.
Referenced by evalOp(), and evalStmt().
{
         return iteration;
     }
InterpreterRelation& souffle::Interpreter::getRelation (const std::string & name) inline protected
Get relation.
Definition at line 130 of file Interpreter.h.
References environment.
Referenced by dropRelation(), evalCond(), evalOp(), evalStmt(), getRelation(), and swapRelation().
{
         // look up relation
         auto pos = environment.find(name);
         assert(pos != environment.end());
         return *pos->second;
     }
InterpreterRelation& souffle::Interpreter::getRelation (const RamRelation & id) inline protected
Get relation.
Definition at line 138 of file Interpreter.h.
References souffle::getName, and getRelation().
{
         return getRelation(id.getName());
     }
relation_map& souffle::Interpreter::getRelationMap () const inline protected
Get relation map.
Definition at line 143 of file Interpreter.h.
References environment.
{
         return const_cast<relation_map&>(environment);
     }
SymbolTable& souffle::Interpreter::getSymbolTable () inline protected
Get symbol table.
Definition at line 89 of file Interpreter.h.
References souffle::RamTranslationUnit::getSymbolTable(), and translationUnit.
Referenced by evalCond(), evalExpr(), and evalStmt().
{
         return translationUnit.getSymbolTable();
     }
RamTranslationUnit& souffle::Interpreter::getTranslationUnit () inline
Get translation unit.
Definition at line 61 of file Interpreter.h.
References executeMain(), executeSubroutine(), and translationUnit.
Referenced by evalCond(), and evalOp().
{
         return translationUnit;
     }
int souffle::Interpreter::incCounter () inline protected
Increment counter.
Definition at line 104 of file Interpreter.h.
References counter.
Referenced by evalExpr().
                      {
         return counter++;
     }
void souffle::Interpreter::incIterationNumber () inline protected
Increment iteration number.
Definition at line 109 of file Interpreter.h.
References iteration.
Referenced by evalStmt().
{
         iteration++;
     }
void* souffle::Interpreter::loadDLL () inline protected
Load dll.
Definition at line 163 of file Interpreter.h.
References dll, and SOUFFLE_DLL.
Referenced by evalExpr().
                     {
         if (dll == nullptr) {
             // check environment variable
             std::string fname = SOUFFLE_DLL;
             dll = dlopen(SOUFFLE_DLL, RTLD_LAZY);
             if (dll == nullptr) {
                 std::cerr << "Cannot find Souffle's DLL" << std::endl;
                 exit(1);
             }
         }
         return dll;
     }
void souffle::Interpreter::resetIterationNumber () inline protected
Reset iteration number.
Definition at line 114 of file Interpreter.h.
References iteration.
Referenced by evalStmt().
{
         iteration = 0;
     }
void souffle::Interpreter::swapRelation (const RamRelation & ramRel1, const RamRelation & ramRel2) inline protected
Swap relation.
Definition at line 155 of file Interpreter.h.
References environment, souffle::RamRelation::getName(), and getRelation().
Referenced by evalStmt().
{
         InterpreterRelation* rel1 = &getRelation(ramRel1);
         InterpreterRelation* rel2 = &getRelation(ramRel2);
         environment[ramRel1.getName()] = rel2;
         environment[ramRel2.getName()] = rel1;
     }
Field Documentation
int souffle::Interpreter::counter private
counter for $ operator
Definition at line 192 of file Interpreter.h.
Referenced by getCounter(), and incCounter().
void* souffle::Interpreter::dll private
Dynamic library for user-defined functors.
Definition at line 198 of file Interpreter.h.
Referenced by loadDLL().
relation_map souffle::Interpreter::environment private
relation environment
Definition at line 183 of file Interpreter.h.
Referenced by createRelation(), dropRelation(), getRelation(), getRelationMap(), swapRelation(), and ~Interpreter().
std::map<std::string, std::map<size_t, size_t> > souffle::Interpreter::frequencies private
counters for atom profiling
Definition at line 186 of file Interpreter.h.
Referenced by evalOp(), and executeMain().
friend souffle::Interpreter::InterpreterProgInterface private
Definition at line 177 of file Interpreter.h.
size_t souffle::Interpreter::iteration private
iteration number (in a fix-point calculation)
Definition at line 195 of file Interpreter.h.
Referenced by getIterationNumber(), incIterationNumber(), and resetIterationNumber().
std::map<std::string, std::atomic<size_t> > souffle::Interpreter::reads private
counters for non-existence checks
Definition at line 189 of file Interpreter.h.
Referenced by evalCond(), and executeMain().
RamTranslationUnit& souffle::Interpreter::translationUnit private
RAM translation Unit.
Definition at line 180 of file Interpreter.h.
Referenced by evalOp(), executeMain(), getSymbolTable(), and getTranslationUnit().
The documentation for this class was generated from the following files:
Interpreter.h
Interpreter.cpp