souffle: souffle::RamAggregate Class Reference
souffle::RamAggregate Class Reference
Aggregation.
#include <RamOperation.h>
Public Types
enum Function { MAX, MIN, COUNT, SUM }
Types of aggregation functions.
Public Member Functions
void addCondition (std::unique_ptr< RamCondition > newCondition)
Add condition.
void apply (const RamNodeMapper &map) override
Apply mapper.
RamAggregate * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
RamCondition * getCondition () const
Get condition.
const RamExpression * getExpression () const
Get target expression.
Function getFunction () const
Get aggregation function.
std::unique_ptr< RamExpression > getIndexElement (RamCondition *c, size_t &element, size_t level)
Get indexable element.
std::vector< RamExpression * > getPattern () const
Get pattern.
SearchColumns getRangeQueryColumns () const
Get range query columns.
const RamRelation & getRelation () const
Get relation.
void print (std::ostream &os, int tabpos) const override
Print.
RamAggregate (std::unique_ptr< RamOperation > nested, Function fun, std::unique_ptr< RamExpression > expression, std::unique_ptr< RamRelationReference > relRef, size_t ident)
Public Member Functions inherited from souffle::RamSearch
std::size_t getIdentifier () const
Get identifier.
RamSearch (RamNodeType type, size_t ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (RamNodeType type, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::unique_ptr< RamCondition > condition
Condition that is checked for each obtained tuple.
std::unique_ptr< RamExpression > expression
Aggregation expression.
Function function
Aggregation function.
SearchColumns keys = 0
Columns to be matched when using a range query.
std::vector< std::unique_ptr< RamExpression > > pattern
Pattern for filtering tuples.
std::unique_ptr< RamRelationReference > relationRef
Aggregation relation.
Protected Attributes inherited from souffle::RamSearch
const size_t identifier
Identifier for the tuple.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Profile text.
Detailed Description
Aggregation.
Definition at line 363 of file RamOperation.h.
Member Enumeration Documentation
enum souffle::RamAggregate::Function
Types of aggregation functions.
Enumerator
MAX
MIN
COUNT
SUM
Definition at line 366 of file RamOperation.h.
 { MAX, MIN, COUNT, SUM };
Constructor & Destructor Documentation
souffle::RamAggregate::RamAggregate (std::unique_ptr< RamOperation > nested, Function fun, std::unique_ptr< RamExpression > expression, std::unique_ptr< RamRelationReference > relRef, size_t ident) inline
Definition at line 368 of file RamOperation.h.
             : RamSearch(RN_Aggregate, ident, std::move(nested)), function(fun),
               expression(std::move(expression)), relationRef(std::move(relRef)),
               pattern(getRelation().getArity()) {}
Member Function Documentation
void souffle::RamAggregate::addCondition (std::unique_ptr< RamCondition > newCondition)
Add condition.
add condition
Definition at line 63 of file RamOperation.cpp.
References condition, souffle::EQ, souffle::RamSearch::getIdentifier(), getIndexElement(), keys, pattern, and relationRef.
{
     assert(RamConditionLevelAnalysis().getLevel(newCondition.get()) == getIdentifier());
     // use condition to narrow scan if possible
     size_t element = 0;
     if (std::unique_ptr<RamExpression> value =
                     getIndexElement(newCondition.get(), element, getIdentifier())) {
         if (element > 0 || relationRef->get()->getName().find("__agg") == std::string::npos) {
             keys |= (1 << element);
             if (pattern[element] == nullptr) {
                 pattern[element] = std::move(value);
             } else {
                 std::unique_ptr<RamExpression> field(new RamElementAccess(getIdentifier(), element));
                 auto addCondition = [&](std::unique_ptr<RamCondition> c) {
                     assert(RamConditionLevelAnalysis().getLevel(c.get()) == getIdentifier());
                     if (condition != nullptr) {
                         condition = std::make_unique<RamConjunction>(std::move(condition), std::move(c));
                     } else {
                         condition = std::move(c);
                     }
                 };
                 addCondition(std::make_unique<RamConstraint>(
                         BinaryConstraintOp::EQ, std::move(field), std::move(value)));
             }
         } else {
             std::unique_ptr<RamExpression> field(new RamElementAccess(getIdentifier(), element));
             std::unique_ptr<RamCondition> eq(
                     new RamConstraint(BinaryConstraintOp::EQ, std::move(field), std::move(value)));
             if (condition != nullptr) {
                 condition = std::make_unique<RamConjunction>(std::move(condition), std::move(eq));
             } else {
                 condition.swap(eq);
             }
         }
     }
 }
void souffle::RamAggregate::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Reimplemented from souffle::RamNestedOperation.
Definition at line 480 of file RamOperation.h.
References souffle::RamNestedOperation::apply().
{
         RamSearch::apply(map);
         if (condition != nullptr) {
             condition = map(std::move(condition));
         }
         relationRef = map(std::move(relationRef));
         if (expression != nullptr) {
             expression = map(std::move(expression));
         }
         for (auto& cur : pattern) {
             if (cur != nullptr) {
                 cur = map(std::move(cur));
             }
         }
     }
RamAggregate* souffle::RamAggregate::clone () const inline override virtual
Create clone.
Implements souffle::RamOperation.
Definition at line 466 of file RamOperation.h.
References souffle::RamOperation::clone(), i, keys, and pattern.
{
         RamAggregate* res = new RamAggregate(std::unique_ptr<RamOperation>(getOperation().clone()), function,
                 expression == nullptr ? nullptr : std::unique_ptr<RamExpression>(expression->clone()),
                 std::unique_ptr<RamRelationReference>(relationRef->clone()), getIdentifier());
         res->keys = keys;
         for (size_t i = 0; i < pattern.size(); ++i) {
             if (pattern[i] != nullptr) {
                 res->pattern[i] = std::unique_ptr<RamExpression>(pattern[i]->clone());
             }
         }
         return res;
     }
bool souffle::RamAggregate::equal (const RamNode & node) const inline override protected virtual
Check equality.
Reimplemented from souffle::RamSearch.
Definition at line 520 of file RamOperation.h.
References souffle::RamSearch::equal(), and souffle::equal_targets().
{
         assert(nullptr != dynamic_cast<const RamAggregate*>(&node));
         const auto& other = static_cast<const RamAggregate&>(node);
         if (getCondition() != nullptr && other.getCondition() != nullptr &&
                 *getCondition() != *other.getCondition()) {
             return false;
         }
         return RamSearch::equal(other) && getCondition() == other.getCondition() &&
                getFunction() == other.getFunction() && getRelation() == other.getRelation() &&
                getExpression() == other.getExpression() && equal_targets(pattern, other.pattern) &&
                getRangeQueryColumns() == other.getRangeQueryColumns();
     }
std::vector<const RamNode*> souffle::RamAggregate::getChildNodes () const inline override virtual
Obtain list of child nodes.
Reimplemented from souffle::RamSearch.
Definition at line 451 of file RamOperation.h.
References souffle::RamSearch::getChildNodes().
{
         auto res = RamSearch::getChildNodes();
         res.push_back(relationRef.get());
         if (condition != nullptr) {
             res.push_back(condition.get());
         }
         for (auto& cur : pattern) {
             if (cur != nullptr) {
                 res.push_back(cur.get());
             }
         }
         return res;
     }
RamCondition* souffle::RamAggregate::getCondition () const inline
Get condition.
Definition at line 376 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode().
{
         return condition.get();
     }
const RamExpression* souffle::RamAggregate::getExpression () const inline
Get target expression.
Definition at line 386 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalOp().
{
         assert(expression);
         return expression.get();
     }
Function souffle::RamAggregate::getFunction () const inline
Get aggregation function.
Definition at line 381 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalOp().
{
         return function;
     }
std::unique_ptr< RamExpression > souffle::RamAggregate::getIndexElement (RamCondition * c, size_t & element, size_t level)
Get indexable element.
get indexable element
Definition at line 35 of file RamOperation.cpp.
References souffle::RamExpression::clone(), souffle::EQ, souffle::RamExpressionLevelAnalysis::getLevel(), souffle::RamConstValueAnalysis::isConstant(), lhs, and rhs.
Referenced by addCondition().
{
     if (auto* binRelOp = dynamic_cast<RamConstraint*>(condition)) {
         if (binRelOp->getOperator() == BinaryConstraintOp::EQ) {
             if (auto* lhs = dynamic_cast<RamElementAccess*>(binRelOp->getLHS())) {
                 RamExpression* rhs = binRelOp->getRHS();
                 if (lhs->getIdentifier() == level &&
                         (RamConstValueAnalysis().isConstant(rhs) ||
                                 RamExpressionLevelAnalysis().getLevel(rhs) < level)) {
                     element = lhs->getElement();
                     return std::unique_ptr<RamExpression>(rhs->clone());
                 }
             }
             if (auto* rhs = dynamic_cast<RamElementAccess*>(binRelOp->getRHS())) {
                 RamExpression* lhs = binRelOp->getLHS();
                 if (rhs->getIdentifier() == level &&
                         (RamConstValueAnalysis().isConstant(lhs) ||
                                 RamExpressionLevelAnalysis().getLevel(lhs) < level)) {
                     element = rhs->getElement();
                     return std::unique_ptr<RamExpression>(lhs->clone());
                 }
             }
         }
     }
     return std::unique_ptr<RamExpression>(nullptr);
 }
std::vector<RamExpression*> souffle::RamAggregate::getPattern () const inline
Get pattern.
Definition at line 397 of file RamOperation.h.
References souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalOp().
{
         return toPtrVector(pattern);
     }
SearchColumns souffle::RamAggregate::getRangeQueryColumns () const inline
Get range query columns.
Definition at line 402 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalOp().
{
         return keys;
     }
const RamRelation& souffle::RamAggregate::getRelation () const inline
Get relation.
Definition at line 392 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalOp().
{
         return *relationRef->get();
     }
void souffle::RamAggregate::print (std::ostream & os, int tabpos) const inline override virtual
Print.
Reimplemented from souffle::RamNestedOperation.
Definition at line 413 of file RamOperation.h.
References souffle::join(), souffle::MAX, souffle::MIN, souffle::RamNestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         switch (function) {
             case MIN:
                 os << "MIN ";
                 break;
             case MAX:
                 os << "MAX ";
                 break;
             case COUNT:
                 os << "COUNT ";
                 break;
             case SUM:
                 os << "SUM ";
                 break;
         }
         if (function != COUNT) {
             os << *expression << " ";
         }
         os << "AS t" << getIdentifier() << ".0 IN t" << getIdentifier() << "  " << getRelation().getName();
         os << "("
            << join(pattern, ",",
                       [&](std::ostream& out, const std::unique_ptr<RamExpression>& expression) {
                           if (expression == nullptr) {
                               out << "_";
                           } else {
                               out << *expression;
                           }
                       })
            << ")";
         if (condition != nullptr) {
             os << " WHERE " << getCondition();
         }
         os << std::endl;
         RamSearch::print(os, tabpos + 1);
     }
Field Documentation
std::unique_ptr<RamCondition> souffle::RamAggregate::condition protected
Condition that is checked for each obtained tuple.
If condition is a nullptr, then no condition applies
Definition at line 502 of file RamOperation.h.
Referenced by addCondition().
std::unique_ptr<RamExpression> souffle::RamAggregate::expression protected
Aggregation expression.
Definition at line 508 of file RamOperation.h.
Function souffle::RamAggregate::function protected
Aggregation function.
Definition at line 505 of file RamOperation.h.
SearchColumns souffle::RamAggregate::keys = 0 protected
Columns to be matched when using a range query.
Definition at line 517 of file RamOperation.h.
Referenced by addCondition(), and clone().
std::vector<std::unique_ptr<RamExpression> > souffle::RamAggregate::pattern protected
Pattern for filtering tuples.
Definition at line 514 of file RamOperation.h.
Referenced by addCondition(), and clone().
std::unique_ptr<RamRelationReference> souffle::RamAggregate::relationRef protected
Aggregation relation.
Definition at line 511 of file RamOperation.h.
Referenced by addCondition().
The documentation for this class was generated from the following files:
RamOperation.h
RamOperation.cpp