souffle: souffle::RamNode Class Reference
souffle::RamNode Class Reference abstract
RamNode is a superclass for all RAM IR classes.
#include <RamNode.h>
Public Member Functions
virtual void apply (const RamNodeMapper &mapper)=0
Apply the mapper to all child nodes.
virtual RamNode * clone () const =0
Create a clone (i.e.
virtual std::vector< const RamNode * > getChildNodes () const =0
Obtain list of all embedded child nodes.
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void print (std::ostream &out=std::cout) const =0
Print RAM node.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
virtual bool equal (const RamNode &other) const =0
Abstract equality check for two RAM nodes.
Private Attributes
const RamNodeType type
Friends
std::ostream & operator<< (std::ostream &out, const RamNode &node)
Print RAM on a stream.
Detailed Description
RamNode is a superclass for all RAM IR classes.
Definition at line 98 of file RamNode.h.
Constructor & Destructor Documentation
souffle::RamNode::RamNode (RamNodeType type) inline
Definition at line 102 of file RamNode.h.
References ~RamNode().
 : type(type) {}
virtual souffle::RamNode::~RamNode () virtual default
A virtual destructor for RAM nodes.
Referenced by RamNode().
Member Function Documentation
virtual void souffle::RamNode::apply (const RamNodeMapper & mapper) pure virtual
Apply the mapper to all child nodes.
Implemented in souffle::RamStratum, souffle::RamDebugInfo, souffle::RamLogTimer, souffle::RamReturn, souffle::RamExit, souffle::RamLoop, souffle::RamProject, souffle::RamParallel, souffle::RamFilter, souffle::RamSequence, souffle::RamAggregate, souffle::RamArgument, souffle::RamQuery, souffle::RamPackRecord, souffle::RamEmptinessCheck, souffle::RamFact, souffle::RamAutoIncrement, souffle::RamSwap, souffle::RamNumber, souffle::RamIndexScan, souffle::RamElementAccess, souffle::RamMerge, souffle::RamAbstractExistenceCheck, souffle::RamUserDefinedOperator, souffle::RamConstraint, souffle::RamRelationReference, souffle::RamRelationSearch, souffle::RamRelation, souffle::RamNegation, souffle::RamProgram, souffle::RamIntrinsicOperator, souffle::RamNestedOperation, souffle::RamConjunction, souffle::RamRelationStatement, and souffle::RamOperation.
Referenced by souffle::ConvertExistenceChecksTransformer::convertExistenceChecks(), souffle::CreateIndicesTransformer::createIndices(), souffle::LevelConditionsTransformer::levelConditions(), and operator!=().
virtual RamNode* souffle::RamNode::clone () const pure virtual
Create a clone (i.e.
deep copy) of this node
Implemented in souffle::RamLogSize, souffle::RamStratum, souffle::RamDebugInfo, souffle::RamLogTimer, souffle::RamReturn, souffle::RamExit, souffle::RamLoop, souffle::RamProject, souffle::RamParallel, souffle::RamFilter, souffle::RamSequence, souffle::RamArgument, souffle::RamAggregate, souffle::RamQuery, souffle::RamPackRecord, souffle::RamEmptinessCheck, souffle::RamFact, souffle::RamAutoIncrement, souffle::RamProvenanceExistenceCheck, souffle::RamUnpackRecord, souffle::RamSwap, souffle::RamNumber, souffle::RamExistenceCheck, souffle::RamIndexScan, souffle::RamMerge, souffle::RamElementAccess, souffle::RamDrop, souffle::RamScan, souffle::RamClear, souffle::RamConstraint, souffle::RamUserDefinedOperator, souffle::RamRelationReference, souffle::RamStore, souffle::RamRelation, souffle::RamLoad, souffle::RamNegation, souffle::RamProgram, souffle::RamIntrinsicOperator, souffle::RamCreate, souffle::RamConjunction, souffle::RamOperation, souffle::RamStatement, souffle::RamCondition, and souffle::RamExpression.
Referenced by operator!=().
virtual bool souffle::RamNode::equal (const RamNode & other) const protected pure virtual
Abstract equality check for two RAM nodes.
Implemented in souffle::RamLogSize, souffle::RamStratum, souffle::RamDebugInfo, souffle::RamLogTimer, souffle::RamReturn, souffle::RamExit, souffle::RamLoop, souffle::RamProject, souffle::RamParallel, souffle::RamFilter, souffle::RamSequence, souffle::RamAggregate, souffle::RamArgument, souffle::RamQuery, souffle::RamPackRecord, souffle::RamEmptinessCheck, souffle::RamFact, souffle::RamAutoIncrement, souffle::RamProvenanceExistenceCheck, souffle::RamUnpackRecord, souffle::RamSwap, souffle::RamNumber, souffle::RamExistenceCheck, souffle::RamIndexScan, souffle::RamElementAccess, souffle::RamMerge, souffle::RamAbstractExistenceCheck, souffle::RamUserDefinedOperator, souffle::RamConstraint, souffle::RamRelationReference, souffle::RamRelationSearch, souffle::RamProgram, souffle::RamNegation, souffle::RamRelation, souffle::RamSearch, souffle::RamIntrinsicOperator, souffle::RamNestedOperation, souffle::RamConjunction, souffle::RamRelationStatement, and souffle::RamOperation.
Referenced by operator==().
virtual std::vector<const RamNode*> souffle::RamNode::getChildNodes () const pure virtual
Obtain list of all embedded child nodes.
Implemented in souffle::RamStratum, souffle::RamDebugInfo, souffle::RamLogTimer, souffle::RamReturn, souffle::RamExit, souffle::RamLoop, souffle::RamProject, souffle::RamParallel, souffle::RamFilter, souffle::RamSequence, souffle::RamArgument, souffle::RamAggregate, souffle::RamQuery, souffle::RamPackRecord, souffle::RamEmptinessCheck, souffle::RamFact, souffle::RamAutoIncrement, souffle::RamSwap, souffle::RamNumber, souffle::RamMerge, souffle::RamElementAccess, souffle::RamIndexScan, souffle::RamAbstractExistenceCheck, souffle::RamScan, souffle::RamConstraint, souffle::RamUserDefinedOperator, souffle::RamRelationReference, souffle::RamRelationSearch, souffle::RamRelation, souffle::RamNegation, souffle::RamSearch, souffle::RamIntrinsicOperator, souffle::RamNestedOperation, souffle::RamConjunction, souffle::RamRelationStatement, souffle::RamOperation, and souffle::RamProgram.
Referenced by operator!=(), souffle::visitDepthFirstPostOrder(), and souffle::visitDepthFirstPreOrder().
RamNodeType souffle::RamNode::getNodeType () const inline
Get type of node.
Definition at line 108 of file RamNode.h.
References type.
Referenced by souffle::RamVisitor< void >::visit().
{
         return type;
     }
bool souffle::RamNode::operator!= (const RamNode & other) const inline
Inequality check for two RAM nodes.
Definition at line 118 of file RamNode.h.
References apply(), clone(), getChildNodes(), and print().
{
         return !(*this == other);
     }
bool souffle::RamNode::operator== (const RamNode & other) const inline
Equivalence check for two RAM nodes.
Definition at line 113 of file RamNode.h.
References equal().
{
         return this == &other || (typeid(*this) == typeid(other) && equal(other));
     }
virtual void souffle::RamNode::print (std::ostream & out = std::cout) const pure virtual
Print RAM node.
Implemented in souffle::RamArgument, souffle::RamPackRecord, souffle::RamEmptinessCheck, souffle::RamAutoIncrement, souffle::RamProvenanceExistenceCheck, souffle::RamNumber, souffle::RamExistenceCheck, souffle::RamElementAccess, souffle::RamRelationReference, souffle::RamConstraint, souffle::RamUserDefinedOperator, souffle::RamNegation, souffle::RamRelation, souffle::RamConjunction, souffle::RamIntrinsicOperator, souffle::RamStatement, souffle::RamOperation, and souffle::RamProgram.
Referenced by operator!=().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const RamNode & node) friend
Print RAM on a stream.
Definition at line 135 of file RamNode.h.
{
         node.print(out);
         return out;
     }
Field Documentation
const RamNodeType souffle::RamNode::type private
Definition at line 99 of file RamNode.h.
Referenced by souffle::RamUserDefinedOperator::clone(), getNodeType(), souffle::RamUserDefinedOperator::getType(), and souffle::RamUserDefinedOperator::print().
The documentation for this class was generated from the following file:
RamNode.h