souffle: souffle::RamOperationDepthAnalysis Class Reference
souffle::RamOperationDepthAnalysis Class Reference
#include <RamOperationDepth.h>
Public Member Functions
size_t getDepth (const RamOperation *op) const
get depth
void run (const RamTranslationUnit &translationUnit) override
run depth analysis for a RAM translation unit
Public Member Functions inherited from souffle::RamAnalysis
virtual void print (std::ostream &os) const
print the analysis result in HTML format
virtual ~RamAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "operation-depth-analysis"
name of analysis
Detailed Description
Definition at line 29 of file RamOperationDepth.h.
Member Function Documentation
size_t souffle::RamOperationDepthAnalysis::getDepth (const RamOperation * op) const
get depth
Get depth of query.
Definition at line 24 of file RamOperationDepth.cpp.
References souffle::RamNestedOperation::getOperation(), and souffle::RamVisitor< R, Params >::visit().
Referenced by souffle::Interpreter::evalOp(), and run().
{
     // visitor
     class OperationDepthVisitor : public RamVisitor<size_t> {
     public:
         // nested operation
         size_t visitNestedOperation(const RamNestedOperation& nestedOp) override {
             return 1 + visit(nestedOp.getOperation());
         }
         // project
         size_t visitProject(const RamProject& project) override {
             return 1;
         }
         // return
         size_t visitReturn(const RamReturn& ret) override {
             return 1;
         }
     };
     return OperationDepthVisitor().visit(op);
 }
void souffle::RamOperationDepthAnalysis::run (const RamTranslationUnit & translationUnit) inline override virtual
run depth analysis for a RAM translation unit
Implements souffle::RamAnalysis.
Definition at line 35 of file RamOperationDepth.h.
References getDepth().
 {}
Field Documentation
constexpr const char* souffle::RamOperationDepthAnalysis::name = "operation-depth-analysis" static
name of analysis
Definition at line 32 of file RamOperationDepth.h.
The documentation for this class was generated from the following files:
RamOperationDepth.h
RamOperationDepth.cpp