souffle: souffle::ConvertExistenceChecksTransformer Class Reference
souffle::ConvertExistenceChecksTransformer Class Reference
#include <RamTransforms.h>
Public Member Functions
bool convertExistenceChecks (RamProgram &program)
std::string getName () const override
Get name of transformer.
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
Apply transformer.
virtual ~RamTransformer ()=default
Protected Member Functions
bool transform (RamTranslationUnit &translationUnit) override
Transform RAM translation unit.
Protected Attributes
RamConditionLevelAnalysis * rcla {nullptr}
RamConstValueAnalysis * rcva {nullptr}
RamExpressionLevelAnalysis * rvla {nullptr}
Detailed Description
Definition at line 83 of file RamTransforms.h.
Member Function Documentation
bool souffle::ConvertExistenceChecksTransformer::convertExistenceChecks (RamProgram & program)
Parameters
program the program to be processed
Returns
whether the program was modified
Definition at line 315 of file RamTransforms.cpp.
References souffle::RamNode::apply(), souffle::RamExpression::clone(), souffle::RamExpressionLevelAnalysis::getLevel(), souffle::RamProgram::getMain(), souffle::identifier(), souffle::RamConstValueAnalysis::isConstant(), souffle::pack(), rcva, rvla, and souffle::visitDepthFirst().
{
     // TODO: Change these to LambdaRamNodeMapper lambdas
     // Node-mapper that searches for and updates RAM scans nested in RAM inserts
     class RamScanCapturer : public RamNodeMapper {
         mutable bool modified = false;
         ConvertExistenceChecksTransformer* context;
     public:
         RamScanCapturer(ConvertExistenceChecksTransformer* c) : context(c) {}
         bool getModified() const {
             return modified;
         }
         bool dependsOn(const RamExpression* value, const size_t identifier) const {
             std::vector<const RamExpression*> queue = {value};
             while (!queue.empty()) {
                 const RamExpression* val = queue.back();
                 queue.pop_back();
                 if (const auto* elemAccess = dynamic_cast<const RamElementAccess*>(val)) {
                     if (context->rvla->getLevel(elemAccess) == identifier) {
                         return true;
                     }
                 } else if (const auto* intrinsicOp = dynamic_cast<const RamIntrinsicOperator*>(val)) {
                     for (const RamExpression* arg : intrinsicOp->getArguments()) {
                         queue.push_back(arg);
                     }
                 } else if (const auto* userDefinedOp = dynamic_cast<const RamUserDefinedOperator*>(val)) {
                     for (const RamExpression* arg : userDefinedOp->getArguments()) {
                         queue.push_back(arg);
                     }
                 }
             }
             return false;
         }
         bool dependsOn(const RamCondition* condition, const size_t identifier) const {
             if (const auto* binRel = dynamic_cast<const RamConstraint*>(condition)) {
                 return dependsOn(binRel->getLHS(), identifier) || dependsOn(binRel->getRHS(), identifier);
             }
             return false;
         }
         std::unique_ptr<RamNode> operator()(std::unique_ptr<RamNode> node) const override {
             if (auto* scan = dynamic_cast<RamRelationSearch*>(node.get())) {
                 const size_t identifier = scan->getIdentifier();
                 bool isExistCheck = true;
                 visitDepthFirst(scan->getOperation(), [&](const RamProject& project) {
                     if (isExistCheck) {
                         std::vector<const RamExpression*> values;
                         // TODO: function to extend vectors
                         const std::vector<RamExpression*> initialVals = project.getValues();
                         values.insert(values.end(), initialVals.begin(), initialVals.end());
                         while (!values.empty()) {
                             const RamExpression* value = values.back();
                             values.pop_back();
                             if (const auto* pack = dynamic_cast<const RamPackRecord*>(value)) {
                                 const std::vector<RamExpression*> args = pack->getArguments();
                                 values.insert(values.end(), args.begin(), args.end());
                             } else if (const auto* intrinsicOp =
                                                dynamic_cast<const RamIntrinsicOperator*>(value)) {
                                 for (auto* arg : intrinsicOp->getArguments()) {
                                     values.push_back(arg);
                                 }
                             } else if (value != nullptr && !context->rcva->isConstant(value) &&
                                        context->rvla->getLevel(value) == identifier) {
                                 isExistCheck = false;
                                 break;
                             }
                         }
                     }
                 });
                 if (isExistCheck) {
                     visitDepthFirst(scan->getOperation(), [&](const RamUnpackRecord& lookup) {
                         if (isExistCheck) {
                             if (lookup.getReferenceLevel() == identifier) {
                                 isExistCheck = false;
                             }
                         }
                     });
                 }
                 if (isExistCheck) {
                     visitDepthFirst(scan->getOperation(), [&](const RamExpression& expression) {
                         if (isExistCheck) {
                             if (dependsOn(&expression, identifier)) {
                                 isExistCheck = false;
                             }
                         }
                     });
                 }
                 if (isExistCheck) {
                     // create constraint
                     std::unique_ptr<RamCondition> constraint;
                     if (nullptr != dynamic_cast<RamScan*>(scan)) {
                         constraint = std::make_unique<RamNegation>(std::make_unique<RamEmptinessCheck>(
                                 std::make_unique<RamRelationReference>(&scan->getRelation())));
                     } else if (auto* indexScan = dynamic_cast<RamIndexScan*>(scan)) {
                         std::vector<std::unique_ptr<RamExpression>> values;
                         for (RamExpression* value : indexScan->getRangePattern()) {
                             if (value != nullptr) {
                                 values.emplace_back(value->clone());
                             } else {
                                 values.push_back(nullptr);
                             }
                         }
                         constraint = std::make_unique<RamExistenceCheck>(
                                 std::make_unique<RamRelationReference>(&scan->getRelation()),
                                 std::move(values));
                     }
                     node = std::make_unique<RamFilter>(std::move(constraint),
                             std::unique_ptr<RamOperation>(scan->getOperation().clone()),
                             scan->getProfileText());
                     modified = true;
                 }
             }
             node->apply(*this);
             return node;
         }
     };
     // Node-mapper that searches for and updates RAM inserts
     class RamQueryCapturer : public RamNodeMapper {
         mutable bool modified;
         ConvertExistenceChecksTransformer* context;
     public:
         RamQueryCapturer(ConvertExistenceChecksTransformer* c) : modified(false), context(c) {}
         bool getModified() const {
             return modified;
         }
         std::unique_ptr<RamNode> operator()(std::unique_ptr<RamNode> node) const override {
             // get all RAM inserts
             if (auto* insert = dynamic_cast<RamQuery*>(node.get())) {
                 RamScanCapturer scanUpdate(context);
                 insert->apply(scanUpdate);
                 if (scanUpdate.getModified()) {
                     modified = true;
                 }
             } else {
                 // no need to search for nested RAM inserts
                 node->apply(*this);
             }
             return node;
         }
     };
     // level all RAM inserts
     RamQueryCapturer insertUpdate(this);
     program.getMain()->apply(insertUpdate);
     return insertUpdate.getModified();
 }
std::string souffle::ConvertExistenceChecksTransformer::getName () const inline override virtual
Get name of transformer.
Implements souffle::RamTransformer.
Definition at line 85 of file RamTransforms.h.
{
         return "ConvertExistenceChecksTransformer";
     }
bool souffle::ConvertExistenceChecksTransformer::transform (RamTranslationUnit & translationUnit) inline override protected virtual
Transform RAM translation unit.
Implements souffle::RamTransformer.
Definition at line 100 of file RamTransforms.h.
References souffle::RamTranslationUnit::getAnalysis(), souffle::RamTranslationUnit::getProgram(), and souffle::LevelConditionsTransformer::rcla.
{
         rcva = translationUnit.getAnalysis<RamConstValueAnalysis>();
         rcla = translationUnit.getAnalysis<RamConditionLevelAnalysis>();
         rvla = translationUnit.getAnalysis<RamExpressionLevelAnalysis>();
         return convertExistenceChecks(*translationUnit.getProgram());
     }
Field Documentation
RamConditionLevelAnalysis* souffle::ConvertExistenceChecksTransformer::rcla {nullptr} protected
Definition at line 97 of file RamTransforms.h.
RamConstValueAnalysis* souffle::ConvertExistenceChecksTransformer::rcva {nullptr} protected
Definition at line 96 of file RamTransforms.h.
Referenced by convertExistenceChecks().
RamExpressionLevelAnalysis* souffle::ConvertExistenceChecksTransformer::rvla {nullptr} protected
Definition at line 98 of file RamTransforms.h.
Referenced by convertExistenceChecks().
The documentation for this class was generated from the following files:
RamTransforms.h
RamTransforms.cpp