souffle: souffle::RamOperation Class Reference
souffle::RamOperation Class Reference abstract
Abstract class for a relational algebra operation.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override=0
Apply mapper.
RamOperation * clone () const override=0
Create clone.
std::vector< const RamNode * > getChildNodes () const override=0
Obtain list of child nodes.
virtual void print (std::ostream &os, int tabpos) const =0
Print.
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override=0
Check equality.
Detailed Description
Abstract class for a relational algebra operation.
Definition at line 37 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamOperation::RamOperation (RamNodeType type) inline
Definition at line 39 of file RamOperation.h.
References print().
 : RamNode(type) {}
Member Function Documentation
void souffle::RamOperation::apply (const RamNodeMapper & map) override pure virtual
Apply mapper.
Implements souffle::RamNode.
Implemented in souffle::RamReturn, souffle::RamProject, souffle::RamFilter, souffle::RamAggregate, souffle::RamIndexScan, souffle::RamRelationSearch, and souffle::RamNestedOperation.
Referenced by print().
RamOperation* souffle::RamOperation::clone () const override pure virtual
Create clone.
Implements souffle::RamNode.
Implemented in souffle::RamReturn, souffle::RamProject, souffle::RamFilter, souffle::RamAggregate, souffle::RamUnpackRecord, souffle::RamIndexScan, and souffle::RamScan.
Referenced by souffle::RamUnpackRecord::clone(), souffle::RamAggregate::clone(), and print().
bool souffle::RamOperation::equal (const RamNode & node) const override protected pure virtual
Check equality.
Implements souffle::RamNode.
Implemented in souffle::RamReturn, souffle::RamProject, souffle::RamFilter, souffle::RamAggregate, souffle::RamUnpackRecord, souffle::RamIndexScan, souffle::RamRelationSearch, souffle::RamSearch, and souffle::RamNestedOperation.
Referenced by print().
std::vector<const RamNode*> souffle::RamOperation::getChildNodes () const override pure virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Implemented in souffle::RamReturn, souffle::RamProject, souffle::RamFilter, souffle::RamAggregate, souffle::RamIndexScan, souffle::RamScan, souffle::RamRelationSearch, souffle::RamSearch, and souffle::RamNestedOperation.
Referenced by print().
virtual void souffle::RamOperation::print (std::ostream & os, int tabpos) const pure virtual
Print.
Implemented in souffle::RamReturn, souffle::RamProject, souffle::RamFilter, souffle::RamAggregate, souffle::RamUnpackRecord, souffle::RamIndexScan, souffle::RamScan, and souffle::RamNestedOperation.
Referenced by print(), and RamOperation().
void souffle::RamOperation::print (std::ostream & os) const inline override virtual
Pretty print.
Implements souffle::RamNode.
Definition at line 45 of file RamOperation.h.
References apply(), clone(), equal(), getChildNodes(), and print().
{
         print(os, 0);
     }
The documentation for this class was generated from the following file:
RamOperation.h