souffle: souffle::RamConjunction Class Reference
souffle::RamConjunction Class Reference
Conjunction.
#include <RamCondition.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply.
RamConjunction * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const RamCondition & getLHS () const
Get left-hand side of conjunction.
const RamCondition & getRHS () const
Get right-hand side of conjunction.
void print (std::ostream &os) const override
Print.
RamConjunction (std::unique_ptr< RamCondition > l, std::unique_ptr< RamCondition > r)
Public Member Functions inherited from souffle::RamCondition
RamCondition (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::unique_ptr< RamCondition > lhs
Left-hand side of conjunction.
std::unique_ptr< RamCondition > rhs
Right-hand side of conjunction.
Detailed Description
Conjunction.
Definition at line 48 of file RamCondition.h.
Constructor & Destructor Documentation
souffle::RamConjunction::RamConjunction (std::unique_ptr< RamCondition > l, std::unique_ptr< RamCondition > r) inline
Definition at line 50 of file RamCondition.h.
             : RamCondition(RN_Conjunction), lhs(std::move(l)), rhs(std::move(r)) {}
Member Function Documentation
void souffle::RamConjunction::apply (const RamNodeMapper & map) inline override virtual
Apply.
Implements souffle::RamNode.
Definition at line 87 of file RamCondition.h.
References lhs, and rhs.
{
         lhs = map(std::move(lhs));
         rhs = map(std::move(rhs));
     }
RamConjunction* souffle::RamConjunction::clone () const inline override virtual
Create clone.
Implements souffle::RamCondition.
Definition at line 80 of file RamCondition.h.
References lhs, and rhs.
{
         RamConjunction* res = new RamConjunction(
                 std::unique_ptr<RamCondition>(lhs->clone()), std::unique_ptr<RamCondition>(rhs->clone()));
         return res;
     }
bool souffle::RamConjunction::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 100 of file RamCondition.h.
References getLHS().
{
         assert(nullptr != dynamic_cast<const RamConjunction*>(&node));
         const auto& other = static_cast<const RamConjunction&>(node);
         return getLHS() == other.getLHS() && getRHS() == other.getRHS();
     }
std::vector<const RamNode*> souffle::RamConjunction::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 75 of file RamCondition.h.
References lhs, and rhs.
{
         return {lhs.get(), rhs.get()};
     }
const RamCondition& souffle::RamConjunction::getLHS () const inline
Get left-hand side of conjunction.
Definition at line 54 of file RamCondition.h.
References lhs.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::Interpreter::evalCond(), and souffle::RamConditionLevelAnalysis::getLevel().
{
         assert(lhs);
         return *lhs;
     }
const RamCondition& souffle::RamConjunction::getRHS () const inline
Get right-hand side of conjunction.
Definition at line 60 of file RamCondition.h.
References rhs.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalCond(), and souffle::RamConditionLevelAnalysis::getLevel().
{
         assert(rhs);
         return *rhs;
     }
void souffle::RamConjunction::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 66 of file RamCondition.h.
References lhs, and rhs.
{
         os << "(";
         lhs->print(os);
         os << " and ";
         rhs->print(os);
         os << ")";
     }
Field Documentation
std::unique_ptr<RamCondition> souffle::RamConjunction::lhs protected
Left-hand side of conjunction.
Definition at line 94 of file RamCondition.h.
std::unique_ptr<RamCondition> souffle::RamConjunction::rhs protected
Right-hand side of conjunction.
Definition at line 97 of file RamCondition.h.
The documentation for this class was generated from the following file:
RamCondition.h