souffle: souffle::LevelConditionsTransformer Class Reference
souffle::LevelConditionsTransformer Class Reference
Hoists the conditions to the earliest point in the loop nest where they can be evaluated.
#include <RamTransforms.h>
Public Member Functions
std::string getName () const override
Get name of transformer.
bool levelConditions (RamProgram &program)
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
Apply transformer.
virtual ~RamTransformer ()=default
Protected Member Functions
bool transform (RamTranslationUnit &translationUnit) override
Transform RAM translation unit.
Protected Attributes
RamConditionLevelAnalysis * rcla {nullptr}
Detailed Description
Hoists the conditions to the earliest point in the loop nest where they can be evaluated.
Definition at line 35 of file RamTransforms.h.
Member Function Documentation
std::string souffle::LevelConditionsTransformer::getName () const inline override virtual
Get name of transformer.
Implements souffle::RamTransformer.
Definition at line 37 of file RamTransforms.h.
References levelConditions().
{
         return "LevelConditionsTransformer";
     }
bool souffle::LevelConditionsTransformer::levelConditions (RamProgram & program)
Parameters
program the program to be processed
Returns
whether the program was modified
identifier for the tuple
Definition at line 51 of file RamTransforms.cpp.
References souffle::RamTransformer::apply(), souffle::RamNode::apply(), souffle::RamCondition::clone(), souffle::RamConditionLevelAnalysis::getLevel(), souffle::RamProgram::getMain(), souffle::identifier(), l, and rcla.
Referenced by getName(), and transform().
{
     // Node-mapper that collects nested conditions which apply to a given scan level
     // TODO: Change these to LambdaRamNodeMapper lambdas
     class RamFilterCapturer : public RamNodeMapper {
         LevelConditionsTransformer* context;
         /** identifier for the tuple */
         const size_t identifier;
         mutable std::unique_ptr<RamCondition> condition;
     public:
         RamFilterCapturer(LevelConditionsTransformer* l, const size_t ident)
                 : context(l), identifier(ident) {}
         std::unique_ptr<RamCondition> getCondition() const {
             return std::move(condition);
         }
         void addCondition(std::unique_ptr<RamCondition> c) const {
             if (condition != nullptr) {
                 condition = std::make_unique<RamConjunction>(std::move(condition), std::move(c));
             } else {
                 condition = std::move(c);
             }
         }
         std::unique_ptr<RamNode> operator()(std::unique_ptr<RamNode> node) const override {
             if (auto* filter = dynamic_cast<RamFilter*>(node.get())) {
                 const RamCondition& condition = filter->getCondition();
                 if (context->rcla->getLevel(&condition) == identifier) {
                     addCondition(std::unique_ptr<RamCondition>(condition.clone()));
                     // skip this filter
                     node->apply(*this);
                     return std::unique_ptr<RamOperation>(filter->getOperation().clone());
                 }
             }
             node->apply(*this);
             return node;
         }
     };
     class RamFilterInsert : public RamNodeMapper {
         std::unique_ptr<RamCondition> condition;
     public:
         RamFilterInsert(std::unique_ptr<RamCondition> c) : condition(std::move(c)) {}
         std::unique_ptr<RamNode> operator()(std::unique_ptr<RamNode> node) const override {
             if (nullptr != dynamic_cast<RamOperation*>(node.get())) {
                 return std::make_unique<RamFilter>(std::unique_ptr<RamCondition>(condition->clone()),
                         std::unique_ptr<RamOperation>(dynamic_cast<RamOperation*>(node.release())));
             }
             return node;
         }
     };
     // Node-mapper that searches for and updates RAM scans nested in RAM inserts
     class RamScanCapturer : public RamNodeMapper {
         mutable bool modified = false;
         LevelConditionsTransformer* context;
     public:
         RamScanCapturer(LevelConditionsTransformer* l) : context(l) {}
         bool getModified() const {
             return modified;
         }
         std::unique_ptr<RamNode> operator()(std::unique_ptr<RamNode> node) const override {
             if (auto* scan = dynamic_cast<RamScan*>(node.get())) {
                 RamFilterCapturer filterUpdate(context, scan->getIdentifier());
                 node->apply(filterUpdate);
                 // If a condition applies to this scan level, filter the scan based on the condition
                 if (std::unique_ptr<RamCondition> condition = filterUpdate.getCondition()) {
                     RamFilterInsert filterInsert(std::move(condition));
                     node->apply(filterInsert);
                     modified = true;
                 }
             }
             node->apply(*this);
             return node;
         }
     };
     // Node-mapper that searches for and updates RAM inserts
     class RamQueryCapturer : public RamNodeMapper {
         mutable bool modified = false;
         LevelConditionsTransformer* context;
     public:
         RamQueryCapturer(LevelConditionsTransformer* l) : context(l) {}
         bool getModified() const {
             return modified;
         }
         std::unique_ptr<RamNode> operator()(std::unique_ptr<RamNode> node) const override {
             // get all RAM inserts
             if (auto* insert = dynamic_cast<RamQuery*>(node.get())) {
                 RamScanCapturer scanUpdate(context);
                 insert->apply(scanUpdate);
                 if (scanUpdate.getModified()) {
                     modified = true;
                 }
             } else {
                 // no need to search for nested RAM inserts
                 node->apply(*this);
             }
             return node;
         }
     };
     // level all RAM inserts
     RamQueryCapturer insertUpdate(this);
     program.getMain()->apply(insertUpdate);
     return insertUpdate.getModified();
 }
bool souffle::LevelConditionsTransformer::transform (RamTranslationUnit & translationUnit) inline override protected virtual
Transform RAM translation unit.
Implements souffle::RamTransformer.
Definition at line 50 of file RamTransforms.h.
References souffle::RamTranslationUnit::getAnalysis(), souffle::RamTranslationUnit::getProgram(), levelConditions(), and rcla.
{
         rcla = translationUnit.getAnalysis<RamConditionLevelAnalysis>();
         return levelConditions(*translationUnit.getProgram());
     }
Field Documentation
RamConditionLevelAnalysis* souffle::LevelConditionsTransformer::rcla {nullptr} protected
Definition at line 48 of file RamTransforms.h.
Referenced by levelConditions(), transform(), and souffle::ConvertExistenceChecksTransformer::transform().
The documentation for this class was generated from the following files:
RamTransforms.h
RamTransforms.cpp