souffle: souffle::RamExpression Class Reference
souffle::RamExpression Class Reference abstract
Abstract class for describing scalar values in RAM.
#include <RamExpression.h>
Public Member Functions
RamExpression * clone () const override=0
Create clone.
RamExpression (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
virtual void apply (const RamNodeMapper &mapper)=0
Apply the mapper to all child nodes.
virtual std::vector< const RamNode * > getChildNodes () const =0
Obtain list of all embedded child nodes.
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void print (std::ostream &out=std::cout) const =0
Print RAM node.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Additional Inherited Members
Protected Member Functions inherited from souffle::RamNode
virtual bool equal (const RamNode &other) const =0
Abstract equality check for two RAM nodes.
Detailed Description
Abstract class for describing scalar values in RAM.
Definition at line 37 of file RamExpression.h.
Constructor & Destructor Documentation
souffle::RamExpression::RamExpression (RamNodeType type) inline
Definition at line 39 of file RamExpression.h.
References clone().
 : RamNode(type) {}
Member Function Documentation
RamExpression* souffle::RamExpression::clone () const override pure virtual
Create clone.
Implements souffle::RamNode.
Implemented in souffle::RamArgument, souffle::RamPackRecord, souffle::RamAutoIncrement, souffle::RamNumber, souffle::RamElementAccess, souffle::RamUserDefinedOperator, and souffle::RamIntrinsicOperator.
Referenced by souffle::RamUserDefinedOperator::clone(), souffle::RamExistenceCheck::clone(), souffle::RamProvenanceExistenceCheck::clone(), souffle::RamPackRecord::clone(), souffle::ConvertExistenceChecksTransformer::convertExistenceChecks(), souffle::CreateIndicesTransformer::getIndexElement(), souffle::RamAggregate::getIndexElement(), and RamExpression().
The documentation for this class was generated from the following file:
RamExpression.h