souffle: souffle::RamNestedOperation Class Reference
souffle::RamNestedOperation Class Reference
Abstract class for nesting operations.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
void print (std::ostream &os, int tabpos) const override
Print.
RamNestedOperation (RamNodeType type, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
RamOperation * clone () const override=0
Create clone.
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Profile text.
Detailed Description
Abstract class for nesting operations.
Definition at line 66 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamNestedOperation::RamNestedOperation (RamNodeType type, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 68 of file RamOperation.h.
             : RamOperation(type), nestedOperation(std::move(nested)), profileText(std::move(profileText)) {}
Member Function Documentation
void souffle::RamNestedOperation::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamOperation.
Reimplemented in souffle::RamFilter, souffle::RamAggregate, souffle::RamIndexScan, and souffle::RamRelationSearch.
Definition at line 93 of file RamOperation.h.
Referenced by souffle::RamRelationSearch::apply(), souffle::RamAggregate::apply(), and souffle::RamFilter::apply().
{
         nestedOperation = map(std::move(nestedOperation));
     }
bool souffle::RamNestedOperation::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamOperation.
Reimplemented in souffle::RamFilter, souffle::RamAggregate, souffle::RamUnpackRecord, souffle::RamIndexScan, souffle::RamRelationSearch, and souffle::RamSearch.
Definition at line 105 of file RamOperation.h.
References getOperation().
Referenced by souffle::RamSearch::equal(), and souffle::RamFilter::equal().
{
         assert(nullptr != dynamic_cast<const RamNestedOperation*>(&node));
         const auto& other = static_cast<const RamNestedOperation&>(node);
         return getOperation() == other.getOperation() && getProfileText() == other.getProfileText();
     }
std::vector<const RamNode*> souffle::RamNestedOperation::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamOperation.
Reimplemented in souffle::RamFilter, souffle::RamAggregate, souffle::RamIndexScan, souffle::RamScan, souffle::RamRelationSearch, and souffle::RamSearch.
Definition at line 88 of file RamOperation.h.
Referenced by souffle::RamSearch::getChildNodes(), and souffle::RamFilter::getChildNodes().
{
         return {nestedOperation.get()};
     }
RamOperation& souffle::RamNestedOperation::getOperation () const inline
Get nested operation.
Definition at line 72 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), souffle::Interpreter::evalOp(), souffle::RamOperationDepthAnalysis::getDepth(), and souffle::CreateIndicesTransformer::rewriteScan().
{
         assert(nullptr != nestedOperation);
         return *nestedOperation;
     }
const std::string& souffle::RamNestedOperation::getProfileText () const inline
Get profile text.
Definition at line 78 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalOp(), souffle::Interpreter::executeMain(), and souffle::CreateIndicesTransformer::rewriteScan().
{
         return profileText;
     }
void souffle::RamNestedOperation::print (std::ostream & os, int tabpos) const inline override virtual
Print.
Implements souffle::RamOperation.
Reimplemented in souffle::RamFilter, souffle::RamAggregate, souffle::RamUnpackRecord, souffle::RamIndexScan, and souffle::RamScan.
Definition at line 83 of file RamOperation.h.
Referenced by souffle::RamScan::print(), souffle::RamIndexScan::print(), souffle::RamUnpackRecord::print(), souffle::RamAggregate::print(), and souffle::RamFilter::print().
{
         nestedOperation->print(os, tabpos + 1);
     }
Field Documentation
std::unique_ptr<RamOperation> souffle::RamNestedOperation::nestedOperation protected
Nested operation.
Definition at line 99 of file RamOperation.h.
const std::string souffle::RamNestedOperation::profileText protected
Profile text.
Definition at line 102 of file RamOperation.h.
The documentation for this class was generated from the following file:
RamOperation.h