souffle: souffle::CreateIndicesTransformer Class Reference
souffle::CreateIndicesTransformer Class Reference
#include <RamTransforms.h>
Public Member Functions
bool createIndices (RamProgram &program)
std::unique_ptr< RamExpression > getIndexElement (RamCondition *c, size_t &element, size_t level)
Get indexable element.
std::string getName () const override
Get name of transformer.
std::unique_ptr< RamOperation > rewriteScan (const RamScan *scan)
Public Member Functions inherited from souffle::RamTransformer
bool apply (RamTranslationUnit &translationUnit)
Apply transformer.
virtual ~RamTransformer ()=default
Protected Member Functions
bool transform (RamTranslationUnit &translationUnit) override
Transform RAM translation unit.
Protected Attributes
RamConstValueAnalysis * rcva {nullptr}
RamExpressionLevelAnalysis * rvla {nullptr}
Detailed Description
Definition at line 56 of file RamTransforms.h.
Member Function Documentation
bool souffle::CreateIndicesTransformer::createIndices (RamProgram & program)
Parameters
program the program to be processed
Returns
whether the program was modified
Definition at line 254 of file RamTransforms.cpp.
References souffle::RamNode::apply(), souffle::RamProgram::getMain(), and rewriteScan().
{
     // TODO: Change these to LambdaRamNodeMapper lambdas
     // Node-mapper that searches for and updates RAM scans nested in RAM inserts
     class RamScanCapturer : public RamNodeMapper {
         mutable bool modified = false;
         CreateIndicesTransformer* context;
     public:
         RamScanCapturer(CreateIndicesTransformer* c) : context(c) {}
         bool getModified() const {
             return modified;
         }
         std::unique_ptr<RamNode> operator()(std::unique_ptr<RamNode> node) const override {
             if (auto* scan = dynamic_cast<RamScan*>(node.get())) {
                 if (std::unique_ptr<RamOperation> op = context->rewriteScan(scan)) {
                     modified = true;
                     node = std::move(op);
                 }
             }
             node->apply(*this);
             return node;
         }
     };
     // Node-mapper that searches for and updates RAM inserts
     class RamQueryCapturer : public RamNodeMapper {
         mutable bool modified;
         CreateIndicesTransformer* context;
     public:
         RamQueryCapturer(CreateIndicesTransformer* c) : modified(false), context(c) {}
         bool getModified() const {
             return modified;
         }
         std::unique_ptr<RamNode> operator()(std::unique_ptr<RamNode> node) const override {
             // get all RAM inserts
             if (auto* insert = dynamic_cast<RamQuery*>(node.get())) {
                 RamScanCapturer scanUpdate(context);
                 insert->apply(scanUpdate);
                 if (!modified && scanUpdate.getModified()) {
                     modified = true;
                 }
             } else {
                 // no need to search for nested RAM inserts
                 node->apply(*this);
             }
             return node;
         }
     };
     // level all RAM inserts
     RamQueryCapturer insertUpdate(this);
     program.getMain()->apply(insertUpdate);
     return insertUpdate.getModified();
 }
std::unique_ptr< RamExpression > souffle::CreateIndicesTransformer::getIndexElement (RamCondition * c, size_t & element, size_t level)
Get indexable element.
Definition at line 179 of file RamTransforms.cpp.
References souffle::RamExpression::clone(), souffle::EQ, souffle::identifier(), lhs, and rhs.
{
     if (auto* binRelOp = dynamic_cast<RamConstraint*>(c)) {
         if (binRelOp->getOperator() == BinaryConstraintOp::EQ) {
             if (auto* lhs = dynamic_cast<RamElementAccess*>(binRelOp->getLHS())) {
                 RamExpression* rhs = binRelOp->getRHS();
                 if (rvla->getLevel(lhs) == identifier &&
                         (rcva->isConstant(rhs) || rvla->getLevel(rhs) < identifier)) {
                     element = lhs->getElement();
                     return std::unique_ptr<RamExpression>(rhs->clone());
                 }
             }
             if (auto* rhs = dynamic_cast<RamElementAccess*>(binRelOp->getRHS())) {
                 RamExpression* lhs = binRelOp->getLHS();
                 if (rvla->getLevel(rhs) == identifier &&
                         (rcva->isConstant(lhs) || rvla->getLevel(lhs) < identifier)) {
                     element = rhs->getElement();
                     return std::unique_ptr<RamExpression>(lhs->clone());
                 }
             }
         }
     }
     return nullptr;
 }
std::string souffle::CreateIndicesTransformer::getName () const inline override virtual
Get name of transformer.
Implements souffle::RamTransformer.
Definition at line 58 of file RamTransforms.h.
{
         return "CreateIndicesTransformer";
     }
std::unique_ptr< RamOperation > souffle::CreateIndicesTransformer::rewriteScan (const RamScan * scan)
Definition at line 204 of file RamTransforms.cpp.
References souffle::RamRelation::getArity(), souffle::RamSearch::getIdentifier(), souffle::RamNestedOperation::getOperation(), souffle::RamNestedOperation::getProfileText(), souffle::RamRelationSearch::getRelation(), and souffle::identifier().
Referenced by createIndices().
{
     if (const auto* filter = dynamic_cast<const RamFilter*>(&scan->getOperation())) {
         const RamRelation& rel = scan->getRelation();
         const size_t identifier = scan->getIdentifier();
         // Values of index per column of table (if indexable)
         std::vector<std::unique_ptr<RamExpression>> queryPattern(rel.getArity());
         // Remaining conditions which weren't handled by an index
         std::unique_ptr<RamCondition> condition;
         auto addCondition = [&](std::unique_ptr<RamCondition> c) {
             if (condition != nullptr) {
                 condition = std::make_unique<RamConjunction>(std::move(condition), std::move(c));
             } else {
                 condition = std::move(c);
             }
         };
         bool indexable = false;
         for (auto& cond : getConditions(&filter->getCondition())) {
             size_t element = 0;
             if (std::unique_ptr<RamExpression> value = getIndexElement(cond.get(), element, identifier)) {
                 indexable = true;
                 if (queryPattern[element] == nullptr) {
                     queryPattern[element] = std::move(value);
                 } else {
                     addCondition(std::move(cond));
                 }
             } else {
                 addCondition(std::move(cond));
             }
         }
         if (indexable) {
             // replace scan by index scan
             return std::make_unique<RamIndexScan>(std::make_unique<RamRelationReference>(&rel), identifier,
                     std::move(queryPattern),
                     condition == nullptr
                             ? std::unique_ptr<RamOperation>(filter->getOperation().clone())
                             : std::make_unique<RamFilter>(std::move(condition),
                                       std::unique_ptr<RamOperation>(filter->getOperation().clone())),
                     scan->getProfileText());
         }
     }
     return nullptr;
 }
bool souffle::CreateIndicesTransformer::transform (RamTranslationUnit & translationUnit) inline override protected virtual
Transform RAM translation unit.
Implements souffle::RamTransformer.
Definition at line 76 of file RamTransforms.h.
References souffle::RamTranslationUnit::getAnalysis(), and souffle::RamTranslationUnit::getProgram().
{
         rcva = translationUnit.getAnalysis<RamConstValueAnalysis>();
         rvla = translationUnit.getAnalysis<RamExpressionLevelAnalysis>();
         return createIndices(*translationUnit.getProgram());
     }
Field Documentation
RamConstValueAnalysis* souffle::CreateIndicesTransformer::rcva {nullptr} protected
Definition at line 73 of file RamTransforms.h.
RamExpressionLevelAnalysis* souffle::CreateIndicesTransformer::rvla {nullptr} protected
Definition at line 74 of file RamTransforms.h.
The documentation for this class was generated from the following files:
RamTransforms.h
RamTransforms.cpp