souffle: souffle::RamConstValueAnalysis Class Reference
souffle::RamConstValueAnalysis Class Reference
#include <RamConstValue.h>
Public Member Functions
bool isConstant (const RamExpression *v) const
constant value
void run (const RamTranslationUnit &translationUnit) override
run const value analysis for a RAM translation unit
Public Member Functions inherited from souffle::RamAnalysis
virtual void print (std::ostream &os) const
print the analysis result in HTML format
virtual ~RamAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "const-value-analysis"
name of analysis
Detailed Description
Definition at line 29 of file RamConstValue.h.
Member Function Documentation
bool souffle::RamConstValueAnalysis::isConstant (const RamExpression * v) const
constant value
Determine whether a RAM value is a constant.
Definition at line 25 of file RamConstValue.cpp.
References souffle::RamIntrinsicOperator::getArguments(), souffle::RamUserDefinedOperator::getArguments(), and souffle::pack().
Referenced by souffle::ConvertExistenceChecksTransformer::convertExistenceChecks(), souffle::RamAggregate::getIndexElement(), and run().
{
     // visitor
     class ConstValueVisitor : public RamVisitor<bool> {
     public:
         // number
         bool visitNumber(const RamNumber& num) override {
             return true;
         }
         // tuple element access
         bool visitElementAccess(const RamElementAccess& elem) override {
             return false;
         }
         // auto increment
         bool visitAutoIncrement(const RamAutoIncrement& increment) override {
             return false;
         }
         // intrinsic functors
         bool visitIntrinsicOperator(const RamIntrinsicOperator& op) override {
             const auto& args = op.getArguments();
             bool isConst = true;
             for (const auto arg : args) {
                 isConst = isConst && visit(arg);
             }
             return isConst;
         }
         // pack operator
         bool visitPackRecord(const RamPackRecord& pack) override {
             return false;
         }
         // argument
         bool visitArgument(const RamArgument& arg) override {
             return false;
         }
         // user defined operator
         bool visitUserDefinedOperator(const RamUserDefinedOperator& op) override {
             const auto& args = op.getArguments();
             bool isConst = true;
             for (const auto arg : args) {
                 isConst = isConst && visit(arg);
             }
             return isConst;
         }
     };
     return ConstValueVisitor().visit(value);
 }
void souffle::RamConstValueAnalysis::run (const RamTranslationUnit & translationUnit) inline override virtual
run const value analysis for a RAM translation unit
Implements souffle::RamAnalysis.
Definition at line 35 of file RamConstValue.h.
References isConstant().
 {}
Field Documentation
constexpr const char* souffle::RamConstValueAnalysis::name = "const-value-analysis" static
name of analysis
Definition at line 32 of file RamConstValue.h.
The documentation for this class was generated from the following files:
RamConstValue.h
RamConstValue.cpp