souffle: souffle::RamConditionLevelAnalysis Class Reference
souffle::RamConditionLevelAnalysis Class Reference
#include <RamConditionLevel.h>
Public Member Functions
size_t getLevel (const RamCondition *condition) const
Get level.
void run (const RamTranslationUnit &translationUnit) override
run level analysis for a RAM translation unit
Public Member Functions inherited from souffle::RamAnalysis
virtual void print (std::ostream &os) const
print the analysis result in HTML format
virtual ~RamAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "condition-level-analysis"
name of analysis
Protected Attributes
RamExpressionLevelAnalysis * rvla
Detailed Description
Definition at line 30 of file RamConditionLevel.h.
Member Function Documentation
size_t souffle::RamConditionLevelAnalysis::getLevel (const RamCondition * condition) const
Get level.
Get level of condition (which for-loop of a query)
Definition at line 33 of file RamConditionLevel.cpp.
References souffle::RamExpressionLevelAnalysis::getLevel(), souffle::RamConjunction::getLHS(), souffle::RamConstraint::getLHS(), souffle::RamNegation::getOperand(), souffle::RamConjunction::getRHS(), souffle::RamConstraint::getRHS(), souffle::RamAbstractExistenceCheck::getValues(), and rvla.
Referenced by souffle::LevelConditionsTransformer::levelConditions().
{
     // visitor
     class ConditionLevelVisitor : public RamVisitor<size_t> {
         RamExpressionLevelAnalysis* rvla;
     public:
         ConditionLevelVisitor(RamExpressionLevelAnalysis* rvla) : rvla(rvla) {}
         // conjunction
         size_t visitConjunction(const RamConjunction& conj) override {
             return std::max(visit(conj.getLHS()), visit(conj.getRHS()));
         }
         // negation
         size_t visitNegation(const RamNegation& neg) override {
             return visit(neg.getOperand());
         }
         // constraint
         size_t visitConstraint(const RamConstraint& binRel) override {
             return std::max(rvla->getLevel(binRel.getLHS()), rvla->getLevel(binRel.getRHS()));
         }
         // existence check
         size_t visitExistenceCheck(const RamExistenceCheck& exists) override {
             size_t level = 0;
             for (const auto& cur : exists.getValues()) {
                 if (cur) {
                     level = std::max(level, rvla->getLevel(cur));
                 }
             }
             return level;
         }
         // provenance existence check
         size_t visitProvenanceExistenceCheck(const RamProvenanceExistenceCheck& provExists) override {
             size_t level = 0;
             for (const auto& cur : provExists.getValues()) {
                 if (cur) {
                     level = std::max(level, rvla->getLevel(cur));
                 }
             }
             return level;
         }
         // emptiness check
         size_t visitEmptinessCheck(const RamEmptinessCheck& emptiness) override {
             return 0;  // can be in the top level
         }
     };
     return ConditionLevelVisitor(rvla).visit(condition);
 }
void souffle::RamConditionLevelAnalysis::run (const RamTranslationUnit & translationUnit) override virtual
run level analysis for a RAM translation unit
Implements souffle::RamAnalysis.
Definition at line 28 of file RamConditionLevel.cpp.
References souffle::RamTranslationUnit::getAnalysis(), and rvla.
{
     rvla = translationUnit.getAnalysis<RamExpressionLevelAnalysis>();
 }
Field Documentation
constexpr const char* souffle::RamConditionLevelAnalysis::name = "condition-level-analysis" static
name of analysis
Definition at line 33 of file RamConditionLevel.h.
RamExpressionLevelAnalysis* souffle::RamConditionLevelAnalysis::rvla protected
Definition at line 42 of file RamConditionLevel.h.
Referenced by getLevel(), and run().
The documentation for this class was generated from the following files:
RamConditionLevel.h
RamConditionLevel.cpp