souffle: souffle::RamExpressionLevelAnalysis Class Reference
souffle::RamExpressionLevelAnalysis Class Reference
#include <RamExpressionLevel.h>
Public Member Functions
size_t getLevel (const RamExpression *value) const
Get level.
void run (const RamTranslationUnit &translationUnit) override
run level analysis for a RAM translation unit
Public Member Functions inherited from souffle::RamAnalysis
virtual void print (std::ostream &os) const
print the analysis result in HTML format
virtual ~RamAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "value-level-analysis"
name of analysis
Detailed Description
Definition at line 27 of file RamExpressionLevel.h.
Member Function Documentation
size_t souffle::RamExpressionLevelAnalysis::getLevel (const RamExpression * value) const
Get level.
Get level of value (which for-loop of a query)
Definition at line 24 of file RamExpressionLevel.cpp.
References souffle::RamIntrinsicOperator::getArguments(), souffle::RamUserDefinedOperator::getArguments(), souffle::RamPackRecord::getArguments(), souffle::RamElementAccess::getIdentifier(), and souffle::pack().
Referenced by souffle::ConvertExistenceChecksTransformer::convertExistenceChecks(), souffle::RamAggregate::getIndexElement(), souffle::RamConditionLevelAnalysis::getLevel(), and run().
{
     // visitor
     class ValueLevelVisitor : public RamVisitor<size_t> {
     public:
         // number
         size_t visitNumber(const RamNumber& num) override {
             return 0;
         }
         // tuple element access
         size_t visitElementAccess(const RamElementAccess& elem) override {
             return elem.getIdentifier();
         }
         // auto increment
         size_t visitAutoIncrement(const RamAutoIncrement& increment) override {
             return 0;
         }
         // intrinsic functors
         size_t visitIntrinsicOperator(const RamIntrinsicOperator& op) override {
             size_t level = 0;
             for (const auto& arg : op.getArguments()) {
                 if (arg != nullptr) {
                     level = std::max(level, visit(arg));
                 }
             }
             return level;
         }
         // pack operator
         size_t visitPackRecord(const RamPackRecord& pack) override {
             size_t level = 0;
             for (const auto& arg : pack.getArguments()) {
                 if (arg) {
                     level = std::max(level, visit(arg));
                 }
             }
             return level;
         }
         // argument
         size_t visitArgument(const RamArgument& arg) override {
             return 0;
         }
         // user defined operator
         size_t visitUserDefinedOperator(const RamUserDefinedOperator& op) override {
             size_t level = 0;
             for (const auto& arg : op.getArguments()) {
                 if (arg != nullptr) {
                     level = std::max(level, visit(arg));
                 }
             }
             return level;
         }
     };
     return ValueLevelVisitor().visit(value);
 }
void souffle::RamExpressionLevelAnalysis::run (const RamTranslationUnit & translationUnit) inline override virtual
run level analysis for a RAM translation unit
Implements souffle::RamAnalysis.
Definition at line 33 of file RamExpressionLevel.h.
References getLevel().
 {}
Field Documentation
constexpr const char* souffle::RamExpressionLevelAnalysis::name = "value-level-analysis" static
name of analysis
Definition at line 30 of file RamExpressionLevel.h.
The documentation for this class was generated from the following files:
RamExpressionLevel.h
RamExpressionLevel.cpp