souffle: souffle::ExplainProvenanceSLD Class Reference
souffle::ExplainProvenanceSLD Class Reference
#include <ExplainProvenanceSLD.h>
Public Member Functions
std::unique_ptr< TreeNode > explain (std::string relName, std::vector< RamDomain > tuple, int ruleNum, int levelNum, size_t depthLimit)
std::unique_ptr< TreeNode > explain (std::string relName, std::vector< std::string > args, size_t depthLimit) override
ExplainProvenanceSLD (SouffleProgram &prog)
std::unique_ptr< TreeNode > explainSubproof (std::string relName, RamDomain subproofNum, size_t depthLimit) override
std::string getRule (std::string relName, size_t ruleNum) override
std::string measureRelation (std::string relName) override
void printRulesJSON (std::ostream &os) override
void setup () override
Public Member Functions inherited from souffle::ExplainProvenance
ExplainProvenance (SouffleProgram &prog)
virtual std::string getRelationOutput (const std::string &relName)
virtual ~ExplainProvenance ()=default
Private Member Functions
std::pair< int, int > findTuple (const std::string &relName, std::vector< RamDomain > tup)
void printRelationOutput (const std::vector< bool > &symMask, const IODirectives &ioDir, const Relation &rel) override
Private Attributes
std::vector< std::string > constraintList
std::map< std::pair< std::string, size_t >, std::vector< std::string > > info
std::map< std::pair< std::string, size_t >, std::string > rules
std::vector< std::vector< RamDomain > > subproofs
Additional Inherited Members
Protected Member Functions inherited from souffle::ExplainProvenance
std::vector< RamDomain > argsToNums (const std::string &relName, std::vector< std::string > &args) const
std::vector< std::string > numsToArgs (const std::string &relName, const std::vector< RamDomain > &nums, std::vector< bool > *err=nullptr) const
Protected Attributes inherited from souffle::ExplainProvenance
SouffleProgram & prog
Detailed Description
Definition at line 33 of file ExplainProvenanceSLD.h.
Constructor & Destructor Documentation
souffle::ExplainProvenanceSLD::ExplainProvenanceSLD (SouffleProgram & prog) inline
Definition at line 35 of file ExplainProvenanceSLD.h.
References setup().
                                                : ExplainProvenance(prog) {
         setup();
     }
Member Function Documentation
std::unique_ptr<TreeNode> souffle::ExplainProvenanceSLD::explain (std::string relName, std::vector< RamDomain > tuple, int ruleNum, int levelNum, size_t depthLimit) inline
Definition at line 71 of file ExplainProvenanceSLD.h.
References arity, constraintList, err, souffle::SouffleProgram::executeSubroutine(), souffle::Relation::getArity(), souffle::SouffleProgram::getRelation(), souffle::SouffleProgram::getSymbolTable(), info, souffle::isNumericBinaryConstraintOp(), souffle::join(), souffle::ExplainProvenance::numsToArgs(), souffle::ExplainProvenance::prog, souffle::SymbolTable::resolve(), subproofs, and souffle::toBinaryConstraintOp().
Referenced by explain(), explainSubproof(), and measureRelation().
{
         std::stringstream joinedArgs;
         joinedArgs << join(numsToArgs(relName, tuple), ", ");
         auto joinedArgsStr = joinedArgs.str();
         // if fact
         if (levelNum == 0) {
             return std::make_unique<LeafNode>(relName + "(" + joinedArgsStr + ")");
         }
         assert(info.find(std::make_pair(relName, ruleNum)) != info.end() && "invalid rule for tuple");
         // if depth limit exceeded
         if (depthLimit <= 1) {
             tuple.push_back(ruleNum);
             tuple.push_back(levelNum);
             // find if subproof exists already
             size_t idx = 0;
             auto it = std::find(subproofs.begin(), subproofs.end(), tuple);
             if (it != subproofs.end()) {
                 idx = it - subproofs.begin();
             } else {
                 subproofs.push_back(tuple);
                 idx = subproofs.size() - 1;
             }
             return std::make_unique<LeafNode>("subproof " + relName + "(" + std::to_string(idx) + ")");
         }
         auto internalNode = std::make_unique<InnerNode>(
                 relName + "(" + joinedArgsStr + ")", "(R" + std::to_string(ruleNum) + ")");
         // make return vector pointer
         std::vector<RamDomain> ret;
         std::vector<bool> err;
         // add level number to tuple
         tuple.push_back(levelNum);
         // execute subroutine to get subproofs
         prog.executeSubroutine(relName + "_" + std::to_string(ruleNum) + "_subproof", tuple, ret, err);
         // recursively get nodes for subproofs
         size_t tupleCurInd = 0;
         for (std::string bodyRel : info[std::make_pair(relName, ruleNum)]) {
             // check whether the current atom is a constraint
             bool isConstraint =
                     std::find(constraintList.begin(), constraintList.end(), bodyRel) != constraintList.end();
             // handle negated atom names
             auto bodyRelAtomName = bodyRel;
             if (bodyRel[0] == '!') {
                 bodyRelAtomName = bodyRel.substr(1);
             }
             // traverse subroutine return
             size_t arity;
             if (isConstraint) {
                 // we only handle binary constraints, and assume arity is 4 to account for hidden provenance
                 // annotations
                 arity = 4;
             } else {
                 arity = prog.getRelation(bodyRelAtomName)->getArity();
             }
             auto tupleEnd = tupleCurInd + arity;
             // store current tuple and error
             std::vector<RamDomain> subproofTuple;
             std::vector<bool> subproofTupleError;
             for (; tupleCurInd < tupleEnd - 2; tupleCurInd++) {
                 subproofTuple.push_back(ret[tupleCurInd]);
                 subproofTupleError.push_back(err[tupleCurInd]);
             }
             int subproofRuleNum = ret[tupleCurInd];
             int subproofLevelNum = ret[tupleCurInd + 1];
             // for a negation, display the corresponding tuple and do not recurse
             if (bodyRel[0] == '!') {
                 std::stringstream joinedTuple;
                 joinedTuple << join(numsToArgs(bodyRelAtomName, subproofTuple, &subproofTupleError), ", ");
                 auto joinedTupleStr = joinedTuple.str();
                 internalNode->add_child(std::make_unique<LeafNode>(bodyRel + "(" + joinedTupleStr + ")"));
                 internalNode->setSize(internalNode->getSize() + 1);
                 // for a binary constraint, display the corresponding values and do not recurse
             } else if (isConstraint) {
                 std::stringstream joinedConstraint;
                 if (isNumericBinaryConstraintOp(toBinaryConstraintOp(bodyRel))) {
                     joinedConstraint << subproofTuple[0] << " " << bodyRel << " " << subproofTuple[1];
                 } else {
                     joinedConstraint << bodyRel << "(\"" << prog.getSymbolTable().resolve(subproofTuple[0])
                                      << "\", \"" << prog.getSymbolTable().resolve(subproofTuple[1]) << "\")";
                 }
                 internalNode->add_child(std::make_unique<LeafNode>(joinedConstraint.str()));
                 internalNode->setSize(internalNode->getSize() + 1);
                 // otherwise, for a normal tuple, recurse
             } else {
                 auto child =
                         explain(bodyRel, subproofTuple, subproofRuleNum, subproofLevelNum, depthLimit - 1);
                 internalNode->setSize(internalNode->getSize() + child->getSize());
                 internalNode->add_child(std::move(child));
             }
             tupleCurInd = tupleEnd;
         }
         return std::move(internalNode);
     }
std::unique_ptr<TreeNode> souffle::ExplainProvenanceSLD::explain (std::string relName, std::vector< std::string > args, size_t depthLimit) inline override virtual
Implements souffle::ExplainProvenance.
Definition at line 185 of file ExplainProvenanceSLD.h.
References souffle::ExplainProvenance::argsToNums(), explain(), and findTuple().
{
         auto tuple = argsToNums(relName, args);
         if (tuple.empty()) {
             return std::make_unique<LeafNode>("Relation not found");
         }
         std::pair<int, int> tupleInfo = findTuple(relName, tuple);
         int ruleNum = tupleInfo.first;
         int levelNum = tupleInfo.second;
         if (ruleNum < 0 || levelNum == -1) {
             return std::make_unique<LeafNode>("Tuple not found");
         }
         return explain(relName, tuple, ruleNum, levelNum, depthLimit);
     }
std::unique_ptr<TreeNode> souffle::ExplainProvenanceSLD::explainSubproof (std::string relName, RamDomain subproofNum, size_t depthLimit) inline override virtual
Implements souffle::ExplainProvenance.
Definition at line 203 of file ExplainProvenanceSLD.h.
References explain(), and subproofs.
{
         if (subproofNum >= (int)subproofs.size()) {
             return std::make_unique<LeafNode>("Subproof not found");
         }
         auto tup = subproofs[subproofNum];
         RamDomain levelNum = tup.back();
         tup.pop_back();
         RamDomain ruleNum = tup.back();
         tup.pop_back();
         return explain(relName, tup, ruleNum, levelNum, depthLimit);
     }
std::pair<int, int> souffle::ExplainProvenanceSLD::findTuple (const std::string & relName, std::vector< RamDomain > tup) inline private
Definition at line 317 of file ExplainProvenanceSLD.h.
References souffle::SouffleProgram::getRelation(), souffle::SouffleProgram::getSymbolTable(), i, souffle::SymbolTable::lookupExisting(), n, and souffle::ExplainProvenance::prog.
Referenced by explain().
{
         auto rel = prog.getRelation(relName);
         if (rel == nullptr) {
             return std::make_pair(-1, -1);
         }
         // find correct tuple
         for (auto& tuple : *rel) {
             bool match = true;
             std::vector<RamDomain> currentTuple;
             for (size_t i = 0; i < rel->getArity() - 2; i++) {
                 RamDomain n;
                 if (*rel->getAttrType(i) == 's') {
                     std::string s;
                     tuple >> s;
                     n = prog.getSymbolTable().lookupExisting(s);
                 } else {
                     tuple >> n;
                 }
                 currentTuple.push_back(n);
                 if (n != tup[i]) {
                     match = false;
                     break;
                 }
             }
             if (match) {
                 RamDomain ruleNum;
                 tuple >> ruleNum;
                 RamDomain levelNum;
                 tuple >> levelNum;
                 return std::make_pair(ruleNum, levelNum);
             }
         }
         // if no tuple exists
         return std::make_pair(-1, -1);
     }
std::string souffle::ExplainProvenanceSLD::getRule (std::string relName, size_t ruleNum) inline override virtual
Implements souffle::ExplainProvenance.
Definition at line 218 of file ExplainProvenanceSLD.h.
References rule, and rules.
{
         auto key = make_pair(relName, ruleNum);
         auto rule = rules.find(key);
         if (rule == rules.end()) {
             return "Rule not found";
         } else {
             return rule->second;
         }
     }
std::string souffle::ExplainProvenanceSLD::measureRelation (std::string relName) inline override virtual
Implements souffle::ExplainProvenance.
Definition at line 229 of file ExplainProvenanceSLD.h.
References explain(), souffle::SouffleProgram::getRelation(), souffle::SouffleProgram::getSymbolTable(), i, souffle::SymbolTable::lookupExisting(), n, souffle::now(), souffle::ExplainProvenance::prog, souffle::Relation::size(), and souffle::profile::ss.
{
         auto rel = prog.getRelation(relName);
         if (rel == nullptr) {
             return "No relation found\n";
         }
         auto size = rel->size();
         int skip = size / 10;
         if (skip == 0) skip = 1;
         std::stringstream ss;
         auto before_time = std::chrono::high_resolution_clock::now();
         int numTuples = 0;
         int proc = 0;
         for (auto& tuple : *rel) {
             auto tupleStart = std::chrono::high_resolution_clock::now();
             if (numTuples % skip != 0) {
                 numTuples++;
                 continue;
             }
             std::vector<RamDomain> currentTuple;
             for (size_t i = 0; i < rel->getArity() - 2; i++) {
                 RamDomain n;
                 if (*rel->getAttrType(i) == 's') {
                     std::string s;
                     tuple >> s;
                     n = prog.getSymbolTable().lookupExisting(s.c_str());
                 } else {
                     tuple >> n;
                 }
                 currentTuple.push_back(n);
             }
             RamDomain ruleNum;
             tuple >> ruleNum;
             RamDomain levelNum;
             tuple >> levelNum;
             std::cout << "Tuples expanded: "
                       << explain(relName, currentTuple, ruleNum, levelNum, 20)->getSize();
             numTuples++;
             proc++;
             auto tupleEnd = std::chrono::high_resolution_clock::now();
             auto tupleDuration =
                     std::chrono::duration_cast<std::chrono::duration<double>>(tupleEnd - tupleStart);
             std::cout << ", Time: " << tupleDuration.count() << "\n";
         }
         auto after_time = std::chrono::high_resolution_clock::now();
         auto duration = std::chrono::duration_cast<std::chrono::duration<double>>(after_time - before_time);
         ss << "total: " << proc << " ";
         ss << duration.count() << std::endl;
         return ss.str();
     }
void souffle::ExplainProvenanceSLD::printRelationOutput (const std::vector< bool > & symMask, const IODirectives & ioDir, const Relation & rel) inline override private virtual
Implements souffle::ExplainProvenance.
Definition at line 362 of file ExplainProvenanceSLD.h.
References souffle::SouffleProgram::getSymbolTable(), souffle::WriteCoutCSVFactory::getWriter(), and souffle::ExplainProvenance::prog.
{
         WriteCoutCSVFactory().getWriter(symMask, prog.getSymbolTable(), ioDir, true)->writeAll(rel);
     }
void souffle::ExplainProvenanceSLD::printRulesJSON (std::ostream & os) inline override virtual
Implements souffle::ExplainProvenance.
Definition at line 296 of file ExplainProvenanceSLD.h.
References rules, and souffle::stringify().
{
         os << "\"rules\": [\n";
         bool first = true;
         for (auto const& cur : rules) {
             if (first)
                 first = false;
             else
                 os << ",\n";
             os << "\t{ \"rule-number\": \"(R" << cur.first.second << ")\", \"rule\": \""
                << stringify(cur.second) << "\"}";
         }
         os << "\n]\n";
     }
void souffle::ExplainProvenanceSLD::setup () inline override virtual
Implements souffle::ExplainProvenance.
Definition at line 39 of file ExplainProvenanceSLD.h.
References souffle::SouffleProgram::getAllRelations(), i, info, souffle::ExplainProvenance::prog, rule, and rules.
Referenced by ExplainProvenanceSLD().
{
         // for each clause, store a mapping from the head relation name to body relation names
         for (auto& rel : prog.getAllRelations()) {
             std::string name = rel->getName();
             // only process info relations
             if (name.find("@info") == std::string::npos) {
                 continue;
             }
             // find all the info tuples
             for (auto& tuple : *rel) {
                 std::vector<std::string> bodyRels;
                 RamDomain ruleNum;
                 tuple >> ruleNum;
                 for (size_t i = 1; i < rel->getArity() - 1; i++) {
                     std::string bodyRel;
                     tuple >> bodyRel;
                     bodyRels.push_back(bodyRel);
                 }
                 std::string rule;
                 tuple >> rule;
                 info.insert({std::make_pair(name.substr(0, name.find(".@info")), ruleNum), bodyRels});
                 rules.insert({std::make_pair(name.substr(0, name.find(".@info")), ruleNum), rule});
             }
         }
     }
Field Documentation
std::vector<std::string> souffle::ExplainProvenanceSLD::constraintList private
Initial value:
= {
            "=", "!=", "<", "<=", ">=", ">", "match", "contains", "not_match", "not_contains"}
Definition at line 314 of file ExplainProvenanceSLD.h.
Referenced by explain().
std::map<std::pair<std::string, size_t>, std::vector<std::string> > souffle::ExplainProvenanceSLD::info private
Definition at line 311 of file ExplainProvenanceSLD.h.
Referenced by explain(), and setup().
std::map<std::pair<std::string, size_t>, std::string> souffle::ExplainProvenanceSLD::rules private
Definition at line 312 of file ExplainProvenanceSLD.h.
Referenced by getRule(), printRulesJSON(), and setup().
std::vector<std::vector<RamDomain> > souffle::ExplainProvenanceSLD::subproofs private
Definition at line 313 of file ExplainProvenanceSLD.h.
Referenced by explain(), and explainSubproof().
The documentation for this class was generated from the following file:
ExplainProvenanceSLD.h