souffle: souffle::RamParallel Class Reference
souffle::RamParallel Class Reference
Parallel block.
#include <RamStatement.h>
Public Member Functions
void add (std::unique_ptr< RamStatement > stmt)
Add new statement to parallel block.
void apply (const RamNodeMapper &map) override
Apply mapper.
RamParallel * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtains a list of child nodes.
std::vector< RamStatement * > getStatements () const
Get statements of parallel block.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
RamParallel ()
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM statement.
RamStatement (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::vector< std::unique_ptr< RamStatement > > statements
list of statements executed in parallel
Detailed Description
Parallel block.
Execute statements in parallel and wait until all statements have completed their execution before completing the execution of the parallel block.
Definition at line 546 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamParallel::RamParallel () inline
Definition at line 548 of file RamStatement.h.
 : RamStatement(RN_Parallel) {}
Member Function Documentation
void souffle::RamParallel::add (std::unique_ptr< RamStatement > stmt) inline
Add new statement to parallel block.
Definition at line 551 of file RamStatement.h.
{
         if (stmt) {
             statements.push_back(std::move(stmt));
         }
     }
void souffle::RamParallel::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 590 of file RamStatement.h.
{
         for (auto& stmt : statements) {
             stmt = map(std::move(stmt));
         }
     }
RamParallel* souffle::RamParallel::clone () const inline override virtual
Create clone.
Implements souffle::RamStatement.
Definition at line 581 of file RamStatement.h.
{
         auto* res = new RamParallel();
         for (auto& cur : statements) {
             res->add(std::unique_ptr<RamStatement>(cur->clone()));
         }
         return res;
     }
bool souffle::RamParallel::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 601 of file RamStatement.h.
References souffle::equal_targets().
{
         assert(nullptr != dynamic_cast<const RamParallel*>(&node));
         const auto& other = static_cast<const RamParallel&>(node);
         return equal_targets(statements, other.statements);
     }
std::vector<const RamNode*> souffle::RamParallel::getChildNodes () const inline override virtual
Obtains a list of child nodes.
Implements souffle::RamNode.
Definition at line 572 of file RamStatement.h.
{
         std::vector<const RamNode*> res;
         for (const auto& cur : statements) {
             res.push_back(cur.get());
         }
         return res;
     }
std::vector<RamStatement*> souffle::RamParallel::getStatements () const inline
Get statements of parallel block.
Definition at line 558 of file RamStatement.h.
References souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalStmt().
{
         return toPtrVector(statements);
     }
void souffle::RamParallel::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print with indentation.
Implements souffle::RamStatement.
Definition at line 563 of file RamStatement.h.
References souffle::times().
{
         os << times(" ", tabpos) << "PARALLEL" << std::endl;
         for (auto const& stmt : statements) {
             stmt->print(os, tabpos + 1);
         }
         os << times(" ", tabpos) << "END PARALLEL" << std::endl;
     }
Field Documentation
std::vector<std::unique_ptr<RamStatement> > souffle::RamParallel::statements protected
list of statements executed in parallel
Definition at line 598 of file RamStatement.h.
The documentation for this class was generated from the following file:
RamStatement.h