souffle: souffle::RamScan Class Reference
souffle::RamScan Class Reference
Relation Scan.
#include <RamOperation.h>
Public Member Functions
RamScan * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
void print (std::ostream &os, int tabpos) const override
Print.
RamScan (std::unique_ptr< RamRelationReference > rel, size_t ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamRelationSearch
void apply (const RamNodeMapper &map) override
Apply mapper.
const RamRelation & getRelation () const
Get search relation.
RamRelationSearch (RamNodeType type, std::unique_ptr< RamRelationReference > relRef, size_t ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamSearch
std::size_t getIdentifier () const
Get identifier.
RamSearch (RamNodeType type, size_t ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (RamNodeType type, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Pretty print.
RamOperation (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Additional Inherited Members
Protected Member Functions inherited from souffle::RamRelationSearch
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes inherited from souffle::RamRelationSearch
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamSearch
const size_t identifier
Identifier for the tuple.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Profile text.
Detailed Description
Relation Scan.
Iterate all tuples of a relation
Definition at line 188 of file RamOperation.h.
Constructor & Destructor Documentation
souffle::RamScan::RamScan (std::unique_ptr< RamRelationReference > rel, size_t ident, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 190 of file RamOperation.h.
             : RamRelationSearch(RN_Scan, std::move(rel), ident, std::move(nested), std::move(profileText)) {}
Member Function Documentation
RamScan* souffle::RamScan::clone () const inline override virtual
Create clone.
Implements souffle::RamOperation.
Definition at line 203 of file RamOperation.h.
{
         return new RamScan(std::unique_ptr<RamRelationReference>(relationRef->clone()), getIdentifier(),
                 std::unique_ptr<RamOperation>(getOperation().clone()), getProfileText());
     }
std::vector<const RamNode*> souffle::RamScan::getChildNodes () const inline override virtual
Obtain list of child nodes.
Reimplemented from souffle::RamRelationSearch.
Definition at line 209 of file RamOperation.h.
References souffle::RamRelationSearch::getChildNodes().
{
         return RamRelationSearch::getChildNodes();
     }
void souffle::RamScan::print (std::ostream & os, int tabpos) const inline override virtual
Print.
Reimplemented from souffle::RamNestedOperation.
Definition at line 195 of file RamOperation.h.
References souffle::RamNestedOperation::print(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "FOR t" << getIdentifier();
         os << " in " << getRelation().getName() << std::endl;
         RamRelationSearch::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
RamOperation.h